/**
 * FashXStudio — Master Screen Inventory
 * Visual Design — 1: Visual Product Architecture + Complete Screen / Page Inventory
 * 123 Canonical Screens across 13 Experience Domains, 11 Templates, and 5 Dependency Groups.
 */

import { ImplementationDependencyGroup, PageTemplateType, ScreenDomain, ScreenMetadata } from "./types";

export const SCREEN_INVENTORY: ScreenMetadata[] = [
  // A. Platform / Entry Screens (8 screens) - Group A: Foundation
  {
    id: "A01",
    screenCode: "A01",
    title: "Landing",
    domain: "platform",
    route: "/landing",
    templateType: "editorial",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F01",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Public landing experience showcasing FashXStudio value proposition.",
  },
  {
    id: "A02",
    screenCode: "A02",
    title: "Sign In",
    domain: "platform",
    route: "/auth/signin",
    templateType: "settings",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "User sign-in authentication screen.",
  },
  {
    id: "A03",
    screenCode: "A03",
    title: "Sign Up",
    domain: "platform",
    route: "/auth/signup",
    templateType: "settings",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "New account registration and consent capture screen.",
  },
  {
    id: "A04",
    screenCode: "A04",
    title: "Account Recovery",
    domain: "platform",
    route: "/auth/recovery",
    templateType: "settings",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Password reset and account recovery workflow.",
  },
  {
    id: "A05",
    screenCode: "A05",
    title: "Verification",
    domain: "platform",
    route: "/auth/verify",
    templateType: "settings",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Email and phone two-factor verification screen.",
  },
  {
    id: "A06",
    screenCode: "A06",
    title: "Onboarding",
    domain: "platform",
    route: "/onboarding",
    templateType: "assistant",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Interactive onboarding wizard for personal fashion setup.",
  },
  {
    id: "A07",
    screenCode: "A07",
    title: "Preference Setup",
    domain: "platform",
    route: "/onboarding/preferences",
    templateType: "settings",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Initial sizing, aesthetics, and preferred brand onboarding setup.",
  },
  {
    id: "A08",
    screenCode: "A08",
    title: "Location / Region Setup",
    domain: "platform",
    route: "/onboarding/location",
    templateType: "settings",
    dependencyGroup: "group_a_foundation",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Geographic region and local climate onboarding calibration.",
  },

  // H. Home Screens (7 screens) - Group B: Core Content
  {
    id: "H01",
    screenCode: "H01",
    title: "Home Dashboard",
    domain: "home",
    route: "/(tabs)/home",
    templateType: "dashboard",
    dependencyGroup: "group_b_core_content",
    navigationType: "tab",
    featureId: "FX-F03",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Dynamic personalized entry point into the FashXStudio ecosystem.",
  },
  {
    id: "H02",
    screenCode: "H02",
    title: "Personalized Home",
    domain: "home",
    route: "/home/personalized",
    templateType: "dashboard",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F09",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Adaptive home feed curated around user's active style identity.",
  },
  {
    id: "H03",
    screenCode: "H03",
    title: "Trending Highlights",
    domain: "home",
    route: "/home/trending",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "High-velocity micro-trends and viral runway fashion highlights.",
  },
  {
    id: "H04",
    screenCode: "H04",
    title: "Recommended Products",
    domain: "home",
    route: "/home/recommended-products",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Algorithmic product carousel matching user's undertone and budget.",
  },
  {
    id: "H05",
    screenCode: "H05",
    title: "Recommended Looks",
    domain: "home",
    route: "/home/recommended-looks",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Complete daily outfit looks assembled by the stylist engine.",
  },
  {
    id: "H06",
    screenCode: "H06",
    title: "Regional Highlights",
    domain: "home",
    route: "/home/regional-highlights",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Geo-contextual fashion trends spotlighting the user's metro area.",
  },
  {
    id: "H07",
    screenCode: "H07",
    title: "Recently Viewed",
    domain: "home",
    route: "/home/recently-viewed",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Chronological stream of inspected garments and lookbooks.",
  },

  // D. Discovery Screens (10 screens) - Group B: Core Content
  {
    id: "D01",
    screenCode: "D01",
    title: "Discovery Home",
    domain: "discovery",
    route: "/(tabs)/discover",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "tab",
    featureId: "FX-F03",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "MMR λ=0.7 diversified daily discovery feed with stylist chips.",
  },
  {
    id: "D02",
    screenCode: "D02",
    title: "Explore Fashion",
    domain: "discovery",
    route: "/discover/fashion",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Visual inspiration browser exploring aesthetics and silhouettes.",
  },
  {
    id: "D03",
    screenCode: "D03",
    title: "Explore Products",
    domain: "discovery",
    route: "/discover/products",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Infinite scroll catalog of normalized multi-merchant apparel.",
  },
  {
    id: "D04",
    screenCode: "D04",
    title: "Explore Looks",
    domain: "discovery",
    route: "/discover/looks",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Curated head-to-toe looks styled across multiple brands.",
  },
  {
    id: "D05",
    screenCode: "D05",
    title: "Explore Collections",
    domain: "discovery",
    route: "/discover/collections",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Thematic capsule collections (Quiet Luxury, Scandinavian, Streetwear).",
  },
  {
    id: "D06",
    screenCode: "D06",
    title: "Explore Brands",
    domain: "discovery",
    route: "/discover/brands",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Directory of merchant and designer fashion brands.",
  },
  {
    id: "D07",
    screenCode: "D07",
    title: "Explore Styles",
    domain: "discovery",
    route: "/discover/styles",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Fashion archetype explorer traversing aesthetics and subcultures.",
  },
  {
    id: "D08",
    screenCode: "D08",
    title: "Explore Trends",
    domain: "discovery",
    route: "/discover/trends",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Curated trend stream tracking seasonal silhouettes and colorways.",
  },
  {
    id: "D09",
    screenCode: "D09",
    title: "Personalized Discovery",
    domain: "discovery",
    route: "/discover/personalized",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F09",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Hyper-tailored discovery eliminating catalog noise.",
  },
  {
    id: "D10",
    screenCode: "D10",
    title: "Discovery Results",
    domain: "discovery",
    route: "/discover/results",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Faceted discovery grid filtered by categories, occasions, or tags.",
  },

  // S. Search Screens (10 screens) - Group B: Core Content
  {
    id: "S01",
    screenCode: "S01",
    title: "Search Home",
    domain: "search",
    route: "/(tabs)/search",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "tab",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Unified search interface with recent queries and trending tags.",
  },
  {
    id: "S02",
    screenCode: "S02",
    title: "Search Suggestions",
    domain: "search",
    route: "/search/suggestions",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Real-time prefix tokenized query autocomplete list.",
  },
  {
    id: "S03",
    screenCode: "S03",
    title: "Product Search Results",
    domain: "search",
    route: "/search/products",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Product-specific matching results grid with sorting controls.",
  },
  {
    id: "S04",
    screenCode: "S04",
    title: "Fashion Search Results",
    domain: "search",
    route: "/search/fashion",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Search results matching editorial stories and lookbooks.",
  },
  {
    id: "S05",
    screenCode: "S05",
    title: "Brand Search Results",
    domain: "search",
    route: "/search/brands",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Search results matching fashion brands and merchants.",
  },
  {
    id: "S06",
    screenCode: "S06",
    title: "Style Search Results",
    domain: "search",
    route: "/search/styles",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Search results matching style archetypes and subcultures.",
  },
  {
    id: "S07",
    screenCode: "S07",
    title: "Trend Search Results",
    domain: "search",
    route: "/search/trends",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Search results matching active fashion trend keywords.",
  },
  {
    id: "S08",
    screenCode: "S08",
    title: "Search Filters",
    domain: "search",
    route: "/search/filters",
    templateType: "settings",
    dependencyGroup: "group_b_core_content",
    navigationType: "modal",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multi-facet filter sheet covering price, colors, brands, and sizing.",
  },
  {
    id: "S09",
    screenCode: "S09",
    title: "Advanced Search",
    domain: "search",
    route: "/search/advanced",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multimodal search allowing image upload and combined query attributes.",
  },
  {
    id: "S10",
    screenCode: "S10",
    title: "Search Empty State",
    domain: "search",
    route: "/search/empty",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Zero-results fallback with spelling corrections and trending items.",
  },

  // P. Product Screens (10 screens) - Group B: Core Content
  {
    id: "P01",
    screenCode: "P01",
    title: "Product Listing",
    domain: "product",
    route: "/products",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Canonical product catalog grid with facet chips and pagination.",
  },
  {
    id: "P02",
    screenCode: "P02",
    title: "Product Detail",
    domain: "product",
    route: "/products/:id",
    templateType: "detail",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "High-information PDP with gallery, price, variants, and primary CTAs.",
  },
  {
    id: "P03",
    screenCode: "P03",
    title: "Product Image Gallery",
    domain: "product",
    route: "/products/:id/gallery",
    templateType: "detail",
    dependencyGroup: "group_b_core_content",
    navigationType: "modal",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Full-screen zoomable high-resolution garment asset gallery.",
  },
  {
    id: "P04",
    screenCode: "P04",
    title: "Product Variant Selection",
    domain: "product",
    route: "/products/:id/variants",
    templateType: "settings",
    dependencyGroup: "group_b_core_content",
    navigationType: "drawer",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Interactive colorway swatch and size picker drawer.",
  },
  {
    id: "P05",
    screenCode: "P05",
    title: "Product Reviews",
    domain: "product",
    route: "/products/:id/reviews",
    templateType: "detail",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Community reviews, ratings, and physical fit observations.",
  },
  {
    id: "P06",
    screenCode: "P06",
    title: "Product Specifications",
    domain: "product",
    route: "/products/:id/specifications",
    templateType: "detail",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Material composition, care guide, fabric weight, and origin.",
  },
  {
    id: "P07",
    screenCode: "P07",
    title: "Similar Products",
    domain: "product",
    route: "/products/:id/similar",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multimodal vector similarity suggestions matching silhouette.",
  },
  {
    id: "P08",
    screenCode: "P08",
    title: "Recommended Products",
    domain: "product",
    route: "/products/:id/recommended",
    templateType: "listing",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Complementary pairing recommendations matching this garment.",
  },
  {
    id: "P09",
    screenCode: "P09",
    title: "Product Comparison",
    domain: "product",
    route: "/products/compare",
    templateType: "comparison",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Side-by-side spec, pricing, merchant, and fit comparison matrix.",
  },
  {
    id: "P10",
    screenCode: "P10",
    title: "Product Availability",
    domain: "product",
    route: "/products/:id/availability",
    templateType: "detail",
    dependencyGroup: "group_b_core_content",
    navigationType: "drawer",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Real-time multi-merchant inventory and stock levels.",
  },

  // SH. Shopping Screens (12 screens) - Group C: Advanced Experiences
  {
    id: "SH01",
    screenCode: "SH01",
    title: "Shopping Home",
    domain: "shopping",
    route: "/shopping",
    templateType: "dashboard",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Commerce hub with cart preview, saved lists, and deals.",
  },
  {
    id: "SH02",
    screenCode: "SH02",
    title: "Category",
    domain: "shopping",
    route: "/shopping/category/:id",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Apparel category browser with subcategory filtering pills.",
  },
  {
    id: "SH03",
    screenCode: "SH03",
    title: "Filter",
    domain: "shopping",
    route: "/shopping/filter",
    templateType: "settings",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "modal",
    featureId: "FX-F11",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Commerce-specific filter covering deals, shipping speed, and sellers.",
  },
  {
    id: "SH04",
    screenCode: "SH04",
    title: "Sort",
    domain: "shopping",
    route: "/shopping/sort",
    templateType: "settings",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "drawer",
    featureId: "FX-F11",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Sort by Price, Popularity, Newest, or Stylist Relevance.",
  },
  {
    id: "SH05",
    screenCode: "SH05",
    title: "Wishlist",
    domain: "shopping",
    route: "/shopping/wishlist",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Saved wishlist with automated price-drop and restock badges.",
  },
  {
    id: "SH06",
    screenCode: "SH06",
    title: "Cart",
    domain: "shopping",
    route: "/shopping/cart",
    templateType: "checkout",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Unified shopping bag with item quantities and pricing subtotal.",
  },
  {
    id: "SH07",
    screenCode: "SH07",
    title: "Cart Detail",
    domain: "shopping",
    route: "/shopping/cart/detail",
    templateType: "checkout",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "drawer",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Merchant breakdown, estimated taxes, and shipping calculation.",
  },
  {
    id: "SH08",
    screenCode: "SH08",
    title: "Checkout",
    domain: "shopping",
    route: "/shopping/checkout",
    templateType: "checkout",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Delivery address, payment method, and affiliate handoff launcher.",
  },
  {
    id: "SH09",
    screenCode: "SH09",
    title: "Order Review",
    domain: "shopping",
    route: "/shopping/order-review",
    templateType: "checkout",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Final pre-submission review of order totals and merchant terms.",
  },
  {
    id: "SH10",
    screenCode: "SH10",
    title: "Order Confirmation",
    domain: "shopping",
    route: "/shopping/order-confirmation",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Success confirmation with tracking tokens and estimated arrivals.",
  },
  {
    id: "SH11",
    screenCode: "SH11",
    title: "Orders",
    domain: "shopping",
    route: "/shopping/orders",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Historical order log across all merchant purchases.",
  },
  {
    id: "SH12",
    screenCode: "SH12",
    title: "Order Detail",
    domain: "shopping",
    route: "/shopping/orders/:id",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Granular order shipment milestones and post-purchase fit survey.",
  },

  // F. Fashion Content Screens (9 screens) - Group B: Core Content
  {
    id: "F01",
    screenCode: "F01",
    title: "Fashion Home",
    domain: "fashion",
    route: "/fashion",
    templateType: "editorial",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Editorial magazine hub curating stories, trends, and lookbooks.",
  },
  {
    id: "F02",
    screenCode: "F02",
    title: "Fashion Feed",
    domain: "fashion",
    route: "/fashion/feed",
    templateType: "editorial",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Continuous editorial stream of runway coverage and style guides.",
  },
  {
    id: "F03",
    screenCode: "F03",
    title: "Fashion Story",
    domain: "fashion",
    route: "/fashion/stories/:id",
    templateType: "editorial",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Rich visual narrative spotlighting a designer, craft, or aesthetic.",
  },
  {
    id: "F04",
    screenCode: "F04",
    title: "Fashion Article",
    domain: "fashion",
    route: "/fashion/articles/:id",
    templateType: "editorial",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "In-depth editorial analysis on fabric innovations and style guides.",
  },
  {
    id: "F05",
    screenCode: "F05",
    title: "Fashion Collection",
    domain: "fashion",
    route: "/fashion/collections/:id",
    templateType: "editorial",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Seasonal designer collections with shoppable product links.",
  },
  {
    id: "F06",
    screenCode: "F06",
    title: "Fashion Look",
    domain: "fashion",
    route: "/fashion/looks/:id",
    templateType: "detail",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "High-res editorial look with interactive garment hotspots.",
  },
  {
    id: "F07",
    screenCode: "F07",
    title: "Fashion Inspiration",
    domain: "fashion",
    route: "/fashion/inspiration",
    templateType: "discovery",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Moodboard feed driven by color themes and cultural aesthetics.",
  },
  {
    id: "F08",
    screenCode: "F08",
    title: "Brand Story",
    domain: "fashion",
    route: "/fashion/brands/:id/story",
    templateType: "editorial",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Behind-the-brand heritage, sustainability ethos, and craftsmanship.",
  },
  {
    id: "F09",
    screenCode: "F09",
    title: "Editorial View",
    domain: "fashion",
    route: "/fashion/editorial/:id",
    templateType: "editorial",
    dependencyGroup: "group_b_core_content",
    navigationType: "stack",
    featureId: "FX-F06",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Immersive full-screen editorial spread.",
  },

  // ST. Outfit / Styling Screens (9 screens) - Group C: Advanced Experiences
  {
    id: "ST01",
    screenCode: "ST01",
    title: "Style Home",
    domain: "style",
    route: "/(tabs)/style",
    templateType: "dashboard",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "tab",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Personal styling studio hub with outfit canvas and saved looks.",
  },
  {
    id: "ST02",
    screenCode: "ST02",
    title: "Outfit Builder",
    domain: "style",
    route: "/style/builder",
    templateType: "builder",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Interactive 2D drag-and-drop outfit layering canvas.",
  },
  {
    id: "ST03",
    screenCode: "ST03",
    title: "Look Builder",
    domain: "style",
    route: "/style/look-builder",
    templateType: "builder",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multi-garment composition tool with compatibility scoring.",
  },
  {
    id: "ST04",
    screenCode: "ST04",
    title: "Mix & Match",
    domain: "style",
    route: "/style/mix-match",
    templateType: "builder",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Slot-machine carousel rotating tops and bottoms against a base item.",
  },
  {
    id: "ST05",
    screenCode: "ST05",
    title: "Style Recommendation",
    domain: "style",
    route: "/style/recommendations",
    templateType: "discovery",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Curated algorithmic outfits matching upcoming calendar events.",
  },
  {
    id: "ST06",
    screenCode: "ST06",
    title: "Outfit Preview",
    domain: "style",
    route: "/style/preview/:id",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "High-resolution preview of combined outfit components.",
  },
  {
    id: "ST07",
    screenCode: "ST07",
    title: "Outfit Detail",
    domain: "style",
    route: "/style/outfits/:id",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Itemized garment breakdown, total outfit price, and shop-all CTAs.",
  },
  {
    id: "ST08",
    screenCode: "ST08",
    title: "Saved Looks",
    domain: "style",
    route: "/style/saved-looks",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "User's personal lookbook of assembled outfits and favorite looks.",
  },
  {
    id: "ST09",
    screenCode: "ST09",
    title: "Style Preferences",
    domain: "style",
    route: "/style/preferences",
    templateType: "settings",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Style archetype, color palette, and modesty preferences configuration.",
  },

  // T. Trends Screens (8 screens) - Group C: Advanced Experiences
  {
    id: "T01",
    screenCode: "T01",
    title: "Trends Home",
    domain: "trends",
    route: "/trends",
    templateType: "dashboard",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Macro and micro trend radar monitoring real-time fashion momentum.",
  },
  {
    id: "T02",
    screenCode: "T02",
    title: "Trending Styles",
    domain: "trends",
    route: "/trends/styles",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Rising aesthetic movements (e.g. Balletcore, Gorpcore, Indie Sleaze).",
  },
  {
    id: "T03",
    screenCode: "T03",
    title: "Trending Products",
    domain: "trends",
    route: "/trends/products",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Products with rapidly spiking demand signals across merchant catalogs.",
  },
  {
    id: "T04",
    screenCode: "T04",
    title: "Trending Categories",
    domain: "trends",
    route: "/trends/categories",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Apparel categories exhibiting seasonal or cyclical breakout growth.",
  },
  {
    id: "T05",
    screenCode: "T05",
    title: "Regional Trends",
    domain: "trends",
    route: "/trends/regional",
    templateType: "map",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Geographic breakdown of style adoption across global metro clusters.",
  },
  {
    id: "T06",
    screenCode: "T06",
    title: "Emerging Trends",
    domain: "trends",
    route: "/trends/emerging",
    templateType: "discovery",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Early signal detection from runway debuts and boutique ateliers.",
  },
  {
    id: "T07",
    screenCode: "T07",
    title: "Trend Detail",
    domain: "trends",
    route: "/trends/:id",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Deep dive on trend origin, adoption curve, and shoppable expressions.",
  },
  {
    id: "T08",
    screenCode: "T08",
    title: "Trend Timeline",
    domain: "trends",
    route: "/trends/:id/timeline",
    templateType: "dashboard",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Historical popularity trajectory and forecast longevity curve.",
  },

  // M. Regional / Maps Screens (10 screens) - Group C: Advanced Experiences
  {
    id: "M01",
    screenCode: "M01",
    title: "Regional Home",
    domain: "regional",
    route: "/maps",
    templateType: "map",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Interactive geographic fashion radar with global clusters.",
  },
  {
    id: "M02",
    screenCode: "M02",
    title: "Fashion Map",
    domain: "regional",
    route: "/maps/fashion",
    templateType: "map",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Full-screen map overlay displaying active regional style signals.",
  },
  {
    id: "M03",
    screenCode: "M03",
    title: "Regional Explorer",
    domain: "regional",
    route: "/maps/explorer",
    templateType: "map",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multi-tier geographic navigation from continent to city borough.",
  },
  {
    id: "M04",
    screenCode: "M04",
    title: "Country View",
    domain: "regional",
    route: "/maps/country/:country_id",
    templateType: "map",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "National fashion trends, domestic designers, and local preferences.",
  },
  {
    id: "M05",
    screenCode: "M05",
    title: "State / Province View",
    domain: "regional",
    route: "/maps/state/:state_id",
    templateType: "map",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "State-level climate adaptations and local shopping hubs.",
  },
  {
    id: "M06",
    screenCode: "M06",
    title: "City View",
    domain: "regional",
    route: "/maps/city/:city_id",
    templateType: "map",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Metropolitan street style, boutique clusters, and local events.",
  },
  {
    id: "M07",
    screenCode: "M07",
    title: "Regional Trends",
    domain: "regional",
    route: "/maps/trends/:region_id",
    templateType: "discovery",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Trending items specifically adopted within selected geographic zone.",
  },
  {
    id: "M08",
    screenCode: "M08",
    title: "Local Products",
    domain: "regional",
    route: "/maps/products/:region_id",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Garments sourced from indigenous craftspersons or regional merchants.",
  },
  {
    id: "M09",
    screenCode: "M09",
    title: "Regional Collections",
    domain: "regional",
    route: "/maps/collections/:region_id",
    templateType: "listing",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Curated fashion collections inspired by regional culture or craft.",
  },
  {
    id: "M10",
    screenCode: "M10",
    title: "Location Detail",
    domain: "regional",
    route: "/maps/location/:location_id",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Detailed borough / neighborhood fashion snapshot and boutique list.",
  },

  // AI. AI Screens (9 screens) - Group C: Advanced Experiences
  {
    id: "AI01",
    screenCode: "AI01",
    title: "AI Home",
    domain: "ai",
    route: "/ai",
    templateType: "assistant",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Central AI intelligence hub with quick stylist query shortcuts.",
  },
  {
    id: "AI02",
    screenCode: "AI02",
    title: "AI Fashion Assistant",
    domain: "ai",
    route: "/ai/assistant",
    templateType: "assistant",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Conversational multi-turn fashion advisor with real-time look assembly.",
  },
  {
    id: "AI03",
    screenCode: "AI03",
    title: "AI Product Assistant",
    domain: "ai",
    route: "/ai/products",
    templateType: "assistant",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Automated product finder and fit suitability evaluator.",
  },
  {
    id: "AI04",
    screenCode: "AI04",
    title: "AI Style Assistant",
    domain: "ai",
    route: "/ai/style",
    templateType: "assistant",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Personalized styling advice based on user's Monk skin tone and build.",
  },
  {
    id: "AI05",
    screenCode: "AI05",
    title: "AI Outfit Recommendation",
    domain: "ai",
    route: "/ai/outfit-recommendations",
    templateType: "discovery",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "AI-synthesized outfits with algorithmic compatibility scoring.",
  },
  {
    id: "AI06",
    screenCode: "AI06",
    title: "AI Search",
    domain: "ai",
    route: "/ai/search",
    templateType: "discovery",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Natural language semantic search understanding aesthetic queries.",
  },
  {
    id: "AI07",
    screenCode: "AI07",
    title: "AI Recommendation Detail",
    domain: "ai",
    route: "/ai/recommendation/:id",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Itemized recommendation card with user controls to modify or accept.",
  },
  {
    id: "AI08",
    screenCode: "AI08",
    title: "AI Result Explanation",
    domain: "ai",
    route: "/ai/explanation/:id",
    templateType: "detail",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "drawer",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Transparent 'Why this recommendation?' breakdown of styling logic.",
  },
  {
    id: "AI09",
    screenCode: "AI09",
    title: "AI Preferences",
    domain: "ai",
    route: "/ai/preferences",
    templateType: "settings",
    dependencyGroup: "group_c_advanced_experiences",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Controls governing AI autonomy, risk tolerance, and color palette bias.",
  },

  // PR. Saved / Personal Screens (11 screens) - Group D: Personalization
  {
    id: "PR01",
    screenCode: "PR01",
    title: "Profile",
    domain: "profile",
    route: "/(tabs)/profile",
    templateType: "dashboard",
    dependencyGroup: "group_d_personalization",
    navigationType: "tab",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Main profile overview with style stats, active avatar, and badges.",
  },
  {
    id: "PR02",
    screenCode: "PR02",
    title: "Personal Dashboard",
    domain: "profile",
    route: "/profile/dashboard",
    templateType: "dashboard",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Activity metrics, wardrobe utilization, and style evolution over time.",
  },
  {
    id: "PR03",
    screenCode: "PR03",
    title: "Saved Products",
    domain: "profile",
    route: "/profile/saved-products",
    templateType: "listing",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Bookmarked individual garments across all merchant platforms.",
  },
  {
    id: "PR04",
    screenCode: "PR04",
    title: "Saved Looks",
    domain: "profile",
    route: "/profile/saved-looks",
    templateType: "listing",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Assembled outfits and complete looks saved for future reference.",
  },
  {
    id: "PR05",
    screenCode: "PR05",
    title: "Saved Fashion",
    domain: "profile",
    route: "/profile/saved-fashion",
    templateType: "listing",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Bookmarked editorial stories, designer collections, and runway articles.",
  },
  {
    id: "PR06",
    screenCode: "PR06",
    title: "Wishlist",
    domain: "profile",
    route: "/profile/wishlist",
    templateType: "listing",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Primary shopping wishlist with notifications for discounts and restocks.",
  },
  {
    id: "PR07",
    screenCode: "PR07",
    title: "Recently Viewed",
    domain: "profile",
    route: "/profile/recently-viewed",
    templateType: "listing",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "History of all viewed garments, looks, and editorial pieces.",
  },
  {
    id: "PR08",
    screenCode: "PR08",
    title: "Preferences",
    domain: "profile",
    route: "/profile/preferences",
    templateType: "settings",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Fashion preferences: sizing, favorite brands, budget, and avoided colors.",
  },
  {
    id: "PR09",
    screenCode: "PR09",
    title: "Recommendation Preferences",
    domain: "profile",
    route: "/profile/recommendation-preferences",
    templateType: "settings",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F09",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Parameters governing recommendation diversity and serendipity.",
  },
  {
    id: "PR10",
    screenCode: "PR10",
    title: "Regional Preferences",
    domain: "profile",
    route: "/profile/regional-preferences",
    templateType: "settings",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Location context overrides, preferred currency, and metric units.",
  },
  {
    id: "PR11",
    screenCode: "PR11",
    title: "Account Settings",
    domain: "profile",
    route: "/profile/settings",
    templateType: "settings",
    dependencyGroup: "group_d_personalization",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Security, notifications, privacy consent, and data erasure controls.",
  },

  // X. System Screens (10 screens) - Group E: Production Quality
  {
    id: "X01",
    screenCode: "X01",
    title: "404 Not Found",
    domain: "system",
    route: "/system/404",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Resource not found error screen with smart redirection CTAs.",
  },
  {
    id: "X02",
    screenCode: "X02",
    title: "403 Forbidden",
    domain: "system",
    route: "/system/403",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Access restricted / consent required boundary screen.",
  },
  {
    id: "X03",
    screenCode: "X03",
    title: "500 Internal Error",
    domain: "system",
    route: "/system/500",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Server exception screen with RFC-7807 trace ID and retry CTA.",
  },
  {
    id: "X04",
    screenCode: "X04",
    title: "Offline",
    domain: "system",
    route: "/system/offline",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Device disconnected state displaying cached wardrobe items.",
  },
  {
    id: "X05",
    screenCode: "X05",
    title: "Maintenance",
    domain: "system",
    route: "/system/maintenance",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Scheduled maintenance window advisory with service status.",
  },
  {
    id: "X06",
    screenCode: "X06",
    title: "Loading",
    domain: "system",
    route: "/system/loading",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Global loading state with brand shimmer placeholders.",
  },
  {
    id: "X07",
    screenCode: "X07",
    title: "Empty",
    domain: "system",
    route: "/system/empty",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Universal zero-data fallback screen with exploratory prompts.",
  },
  {
    id: "X08",
    screenCode: "X08",
    title: "Error Recovery",
    domain: "system",
    route: "/system/error-recovery",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Step-by-step state recovery and session re-synchronization screen.",
  },
  {
    id: "X09",
    screenCode: "X09",
    title: "Permission",
    domain: "system",
    route: "/system/permission",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Hardware camera / photo library / location permission request.",
  },
  {
    id: "X10",
    screenCode: "X10",
    title: "Unsupported State",
    domain: "system",
    route: "/system/unsupported",
    templateType: "dashboard",
    dependencyGroup: "group_e_production_quality",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Device viewport or browser capability mismatch guidance.",
  },
];

export function getScreenById(id: string): ScreenMetadata | undefined {
  return SCREEN_INVENTORY.find((screen) => screen.id === id || screen.screenCode === id);
}

export function getScreenByRoute(route: string): ScreenMetadata | undefined {
  return SCREEN_INVENTORY.find((screen) => screen.route === route);
}

export function getScreensByDomain(domain: ScreenDomain | string): ScreenMetadata[] {
  return SCREEN_INVENTORY.filter((screen) => screen.domain === domain);
}

export function getScreensByTemplate(template: PageTemplateType | string): ScreenMetadata[] {
  return SCREEN_INVENTORY.filter((screen) => screen.templateType === template);
}

export function getScreensByDependencyGroup(group: ImplementationDependencyGroup | string): ScreenMetadata[] {
  return SCREEN_INVENTORY.filter((screen) => screen.dependencyGroup === group);
}
