/**
 * FashXStudio — Master Screen Inventory
 * Phase 01: Visual Product Architecture
 */

import { ScreenMetadata } from "./types";

export const SCREEN_INVENTORY: ScreenMetadata[] = [
  // 1. Onboarding & Identity
  {
    id: "SCR-ONB-01",
    title: "Welcome & Value Proposition",
    domain: "onboarding",
    route: "/onboarding/welcome",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Welcome carousel outlining AI styling value proposition.",
  },
  {
    id: "SCR-ONB-02",
    title: "Biometric & Privacy Consent Gate",
    domain: "onboarding",
    route: "/onboarding/consent",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "GDPR/DPDP biometric consent gate for ephemeral portrait processing.",
  },
  {
    id: "SCR-ONB-03",
    title: "Portrait Capture & Quality Inspection Gate",
    domain: "onboarding",
    route: "/onboarding/capture",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: true,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Camera capture with posture guides and lighting quality gate.",
  },
  {
    id: "SCR-ONB-04",
    title: "Monk Skin Tone & Undertone Calibration",
    domain: "onboarding",
    route: "/onboarding/calibration",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: true,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "10-point Monk Skin Tone (MST) scale & undertone calibration.",
  },
  {
    id: "SCR-ONB-05",
    title: "Sizing & Fit Baseline Questionnaire",
    domain: "onboarding",
    route: "/onboarding/sizing",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Baseline height, body silhouette, and preferred sizing questionnaire.",
  },

  // 2. Discovery & Feed
  {
    id: "SCR-DISC-01",
    title: "Personalized Discovery Feed",
    domain: "discovery",
    route: "/(tabs)/discover",
    navigationType: "tab",
    featureId: "FX-F03",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "MMR λ=0.7 diversified daily outfit recommendations.",
  },
  {
    id: "SCR-DISC-02",
    title: "Trending & Viral Style Radar",
    domain: "discovery",
    route: "/discover/trending",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Real-time macro/micro fashion trend signals across runway & social.",
  },
  {
    id: "SCR-DISC-03",
    title: "Curated Capsule Collections",
    domain: "discovery",
    route: "/discover/capsules",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Thematic curated capsules (Quiet Luxury, Minimalist, Techwear).",
  },
  {
    id: "SCR-DISC-04",
    title: "Category Hub Explorer",
    domain: "discovery",
    route: "/discover/categories",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Taxonomy browser traversing apparel categories and silhouettes.",
  },
  {
    id: "SCR-DISC-05",
    title: "Occasion & Weather-Driven Discovery",
    domain: "discovery",
    route: "/discover/occasions",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Looks filtered by local climate forecast and calendar events.",
  },
  {
    id: "SCR-DISC-06",
    title: "Daily Stylist Rationale Feed",
    domain: "discovery",
    route: "/discover/daily-rationale",
    navigationType: "stack",
    featureId: "FX-F03",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Aesthetic explanations of why today's palette flatters user's undertone.",
  },

  // 3. Search & Filters
  {
    id: "SCR-SRCH-01",
    title: "Unified Search & Autocomplete",
    domain: "search",
    route: "/(tabs)/search",
    navigationType: "tab",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Instant search with prefix tokenization and query chips.",
  },
  {
    id: "SCR-SRCH-02",
    title: "Search Results & Faceted Grid",
    domain: "search",
    route: "/search/results",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Infinite scroll product grid with active facet pills.",
  },
  {
    id: "SCR-SRCH-03",
    title: "Multi-Dimensional Filter Sheet",
    domain: "search",
    route: "/search/filters",
    navigationType: "modal",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Comprehensive filter sheet covering price, brands, colors, and fit.",
  },
  {
    id: "SCR-SRCH-04",
    title: "Visual Similarity & Camera Search",
    domain: "search",
    route: "/search/visual",
    navigationType: "stack",
    featureId: "FX-F04",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multimodal 512-dim vector similarity search via snapshot upload.",
  },

  // 4. Product Detail
  {
    id: "SCR-PROD-01",
    title: "Product Detail Page (PDP)",
    domain: "product",
    route: "/product/[id]",
    navigationType: "stack",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Hero zoomable gallery, normalized price, and variant selector.",
  },
  {
    id: "SCR-PROD-02",
    title: "Size Chart & Fit Recommendation",
    domain: "product",
    route: "/product/[id]/size-guide",
    navigationType: "modal",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Centimeter normalized size conversion table and fit bias.",
  },
  {
    id: "SCR-PROD-03",
    title: "Merchant Stock & Price Comparison",
    domain: "product",
    route: "/product/[id]/merchants",
    navigationType: "drawer",
    featureId: "FX-F05",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Price and stock comparison across Amazon, Myntra, and Flipkart.",
  },
  {
    id: "SCR-PROD-04",
    title: "Stylist Compatibility Rationale",
    domain: "product",
    route: "/product/[id]/rationale",
    navigationType: "drawer",
    featureId: "FX-F05",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "AI Stylist breakdown of color harmony and silhouette alignment.",
  },

  // 5. Virtual Try-On
  {
    id: "SCR-VTO-01",
    title: "Virtual Fitting Canvas",
    domain: "vto",
    route: "/(tabs)/tryon",
    navigationType: "tab",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: true,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Fitting canvas displaying user's calibrated avatar with garments.",
  },
  {
    id: "SCR-VTO-02",
    title: "Garment Layering & Swap Drawer",
    domain: "vto",
    route: "/tryon/layers",
    navigationType: "drawer",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: true,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Z-index garment stack manager: toggle tops, bottoms, outerwear.",
  },
  {
    id: "SCR-VTO-03",
    title: "202 Async Try-On Waiting Room",
    domain: "vto",
    route: "/tryon/progress/[job_id]",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: true,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Live GPU synthesis progress monitor with animated shimmer.",
  },
  {
    id: "SCR-VTO-04",
    title: "Try-On Inspection & C2PA Provenance",
    domain: "vto",
    route: "/tryon/result/[render_id]",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: true,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "High-res render inspection with C2PA digital watermark disclosure.",
  },
  {
    id: "SCR-VTO-05",
    title: "Try-On Realism & Fit Feedback Dialogue",
    domain: "vto",
    route: "/tryon/feedback/[render_id]",
    navigationType: "modal",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Realism score rating and physical fit feedback survey.",
  },

  // 6. Wardrobe / Closet
  {
    id: "SCR-CLST-01",
    title: "Digital Wardrobe Grid",
    domain: "closet",
    route: "/(tabs)/closet",
    navigationType: "tab",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Virtual closet organized by categories with filter pills.",
  },
  {
    id: "SCR-CLST-02",
    title: "Saved Snapshot Item Detail",
    domain: "closet",
    route: "/closet/item/[id]",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Frozen point-in-time pricing and high-res render snapshot.",
  },
  {
    id: "SCR-CLST-03",
    title: "Wardrobe Digitizer & Photo Ingest",
    domain: "closet",
    route: "/closet/digitize",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Auto background removal to digitize user's physical wardrobe.",
  },
  {
    id: "SCR-CLST-04",
    title: "Wardrobe Color Harmony & Gap Analyzer",
    domain: "closet",
    route: "/closet/analytics",
    navigationType: "stack",
    featureId: "FX-F10",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Palette distribution chart and wardrobe gap insights.",
  },

  // 7. Outfit & Style Studio
  {
    id: "SCR-OUTF-01",
    title: "Interactive Outfit Studio",
    domain: "outfit",
    route: "/outfits/studio",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "2D styling canvas allowing drag-and-drop layering and moodboard creation.",
  },
  {
    id: "SCR-OUTF-02",
    title: "AI Generated Lookbooks",
    domain: "outfit",
    route: "/outfits/lookbooks",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Curated lookbooks assembled using multimodal compatibility.",
  },
  {
    id: "SCR-OUTF-03",
    title: "Mix-and-Match Matrix",
    domain: "outfit",
    route: "/outfits/mix-match",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Slot carousel rotating tops, bottoms, and jackets against a base item.",
  },
  {
    id: "SCR-OUTF-04",
    title: "Occasion Lookbook Builder",
    domain: "outfit",
    route: "/outfits/builder",
    navigationType: "stack",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Step-by-step outfit wizard configured for specific occasions.",
  },
  {
    id: "SCR-OUTF-05",
    title: "Outfit Publishing & Export Sheet",
    domain: "outfit",
    route: "/outfits/share/[id]",
    navigationType: "modal",
    featureId: "FX-F07",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Export social look cards with affiliate tags and composite badges.",
  },

  // 8. Shopping & Commerce
  {
    id: "SCR-SHOP-01",
    title: "Universal Wishlist & Price Tracker",
    domain: "shopping",
    route: "/shopping/wishlist",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Universal wishlist featuring automated price drop alerts.",
  },
  {
    id: "SCR-SHOP-02",
    title: "Unified Shopping Bag",
    domain: "shopping",
    route: "/shopping/cart",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Aggregated cart showing merchant breakdown and delivery dates.",
  },
  {
    id: "SCR-SHOP-03",
    title: "Outbound Merchant Affiliate Handoff",
    domain: "shopping",
    route: "/shopping/checkout-handoff",
    navigationType: "modal",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Tracking token generator (fashx_{uid}_{token}) dispatching to merchant.",
  },
  {
    id: "SCR-SHOP-04",
    title: "Order History & Shipment Tracker",
    domain: "shopping",
    route: "/shopping/orders",
    navigationType: "stack",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multi-merchant shipment status milestones with delivery tracking.",
  },
  {
    id: "SCR-SHOP-05",
    title: "Post-Purchase Fit Ledger Survey",
    domain: "shopping",
    route: "/shopping/fit-survey/[order_id]",
    navigationType: "modal",
    featureId: "FX-F11",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Structured feedback collection driving community brand sizing bias.",
  },

  // 9. Regional & Geography
  {
    id: "SCR-GEO-01",
    title: "Global & Regional Fashion Radar Map",
    domain: "regional",
    route: "/regional/map",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Geographic heatmap visualizing real-time fashion aesthetic clusters.",
  },
  {
    id: "SCR-GEO-02",
    title: "City & Street-Style Micro Hub",
    domain: "regional",
    route: "/regional/city/[city_id]",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Localized fashion feed spotlighting trends in key fashion capitals.",
  },
  {
    id: "SCR-GEO-03",
    title: "Local Artisan & Boutique Directory",
    domain: "regional",
    route: "/regional/artisans",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Discovery of indigenous fabrics, regional crafts, and ateliers.",
  },
  {
    id: "SCR-GEO-04",
    title: "Climate-Adaptive Wardrobe Forecast",
    domain: "regional",
    route: "/regional/climate",
    navigationType: "stack",
    featureId: "FX-F12",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Weather outlook matched with breathability and layering advisory.",
  },

  // 10. AI Intelligence & Stylist Hub
  {
    id: "SCR-AI-01",
    title: "AI Conversational Fashion Assistant",
    domain: "intelligence",
    route: "/ai/assistant",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Context-aware chat assistant for multi-turn outfit queries.",
  },
  {
    id: "SCR-AI-02",
    title: "Color Wheel & Harmony Inspector",
    domain: "intelligence",
    route: "/ai/color-harmony",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Visual color wheel displaying complementary and analogous palettes.",
  },
  {
    id: "SCR-AI-03",
    title: "Wardrobe Gap & Acquisition Advisory",
    domain: "intelligence",
    route: "/ai/wardrobe-gaps",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Graph analysis identifying missing versatile wardrobe staples.",
  },
  {
    id: "SCR-AI-04",
    title: "Trend Velocity & Lifecycle Predictor",
    domain: "intelligence",
    route: "/ai/trends",
    navigationType: "stack",
    featureId: "FX-F08",
    requiresAuth: false,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Time-series chart showing micro-trend growth and saturation curves.",
  },

  // 11. Profile & Preferences
  {
    id: "SCR-PROF-01",
    title: "User Style Identity Profile",
    domain: "profile",
    route: "/(tabs)/profile",
    navigationType: "tab",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Profile header, active avatar, style archetype badges, and stats.",
  },
  {
    id: "SCR-PROF-02",
    title: "Style & Brand Preferences Editor",
    domain: "profile",
    route: "/profile/preferences",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Preferred aesthetics, budget ceilings, and avoided colors editor.",
  },
  {
    id: "SCR-PROF-03",
    title: "Avatar & Biometric Gallery Manager",
    domain: "profile",
    route: "/profile/avatars",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: true,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Manage reference portrait photos used for try-on GPU inference.",
  },
  {
    id: "SCR-PROF-04",
    title: "Privacy Consent & Cascading Deletion",
    domain: "profile",
    route: "/profile/privacy",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "GDPR/DPDP compliance center with cascading hard-erasure triggers.",
  },
  {
    id: "SCR-PROF-05",
    title: "Settings, Units & Accessibility Options",
    domain: "profile",
    route: "/profile/settings",
    navigationType: "stack",
    featureId: "FX-F02",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Unit selection, high contrast mode, and notification preferences.",
  },

  // 12. Admin & Telemetry
  {
    id: "SCR-ADM-01",
    title: "Release Gates G1-G6 Verification Console",
    domain: "admin",
    route: "/admin/release-gates",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Monitors G1 functional pass rate, G2 ML calibration, G3 latency.",
  },
  {
    id: "SCR-ADM-02",
    title: "Catalog Ingestion & dHash Telemetry",
    domain: "admin",
    route: "/admin/catalog-ingestion",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "Multi-merchant scraper health and perceptual hash collision metrics.",
  },
  {
    id: "SCR-ADM-03",
    title: "GPU Worker & Try-On Cache Monitor",
    domain: "admin",
    route: "/admin/vto-telemetry",
    navigationType: "stack",
    featureId: "FX-F00",
    requiresAuth: true,
    requiresBiometricConsent: false,
    supportedBreakpoints: ["xs", "sm", "md", "lg", "xl"],
    description: "GPU queue latency, 202 job state transitions, and cache hit ratios.",
  },
];

export function getScreenById(id: string): ScreenMetadata | undefined {
  return SCREEN_INVENTORY.find((screen) => screen.id === id);
}

export function getScreenByRoute(route: string): ScreenMetadata | undefined {
  return SCREEN_INVENTORY.find((screen) => screen.route === route);
}

export function getScreensByDomain(domain: string): ScreenMetadata[] {
  return SCREEN_INVENTORY.filter((screen) => screen.domain === domain);
}
