[mypy]
python_version = 3.12
mypy_path = backend
explicit_package_bases = True
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
exclude = (?x)(^apps/|^docs/)
plugins = pydantic.mypy

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True

[mypy-fashx.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True

[mypy-workers.*]
ignore_errors = True

[mypy-schemas.visual.*]
ignore_errors = True
