"""Master Screen Inventory Catalog for FashXStudio — Visual Design 1.

Defines the complete canonical inventory of 123 screens across all 13 experience domains,
classifying each screen into one of the 11 Reusable Page Templates and 5 Dependency Groups,
and binding each screen to its underlying Feature Platform capability (FX-F00 through FX-F16).
"""

from schemas.visual.v1 import (
    BreakpointConfig,
    DeviceBreakpoint,
    ImplementationDependencyGroup,
    NavigationType,
    PageTemplateType,
    ScreenDefinition,
    ScreenDomain,
    ScreenInventoryRegistry,
)

CANONICAL_SCREENS: list[ScreenDefinition] = [
    # =========================================================================
    # A. Platform / Entry Screens (8 screens) - Dependency Group A: Foundation
    # =========================================================================
    ScreenDefinition(
        screen_id="A01",
        screen_code="A01",
        title="Landing",
        domain=ScreenDomain.PLATFORM,
        route="/landing",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F01",
        requires_auth=False,
        description="Public landing experience showcasing FashXStudio value proposition.",
    ),
    ScreenDefinition(
        screen_id="A02",
        screen_code="A02",
        title="Sign In",
        domain=ScreenDomain.PLATFORM,
        route="/auth/signin",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=False,
        description="User sign-in authentication screen.",
    ),
    ScreenDefinition(
        screen_id="A03",
        screen_code="A03",
        title="Sign Up",
        domain=ScreenDomain.PLATFORM,
        route="/auth/signup",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=False,
        description="New account registration and consent capture screen.",
    ),
    ScreenDefinition(
        screen_id="A04",
        screen_code="A04",
        title="Account Recovery",
        domain=ScreenDomain.PLATFORM,
        route="/auth/recovery",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=False,
        description="Password reset and account recovery workflow.",
    ),
    ScreenDefinition(
        screen_id="A05",
        screen_code="A05",
        title="Verification",
        domain=ScreenDomain.PLATFORM,
        route="/auth/verify",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=False,
        description="Email and phone two-factor verification screen.",
    ),
    ScreenDefinition(
        screen_id="A06",
        screen_code="A06",
        title="Onboarding",
        domain=ScreenDomain.PLATFORM,
        route="/onboarding",
        template_type=PageTemplateType.ASSISTANT,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        description="Interactive onboarding wizard for personal fashion setup.",
    ),
    ScreenDefinition(
        screen_id="A07",
        screen_code="A07",
        title="Preference Setup",
        domain=ScreenDomain.PLATFORM,
        route="/onboarding/preferences",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        description="Initial sizing, aesthetics, and preferred brand onboarding setup.",
    ),
    ScreenDefinition(
        screen_id="A08",
        screen_code="A08",
        title="Location / Region Setup",
        domain=ScreenDomain.PLATFORM,
        route="/onboarding/location",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_A_FOUNDATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=True,
        description="Geographic region and local climate onboarding calibration.",
    ),

    # =========================================================================
    # H. Home Screens (7 screens) - Dependency Group B: Core Content
    # =========================================================================
    ScreenDefinition(
        screen_id="H01",
        screen_code="H01",
        title="Home Dashboard",
        domain=ScreenDomain.HOME,
        route="/(tabs)/home",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.TAB,
        feature_id="FX-F03",
        requires_auth=True,
        description="Dynamic personalized entry point into the FashXStudio ecosystem.",
    ),
    ScreenDefinition(
        screen_id="H02",
        screen_code="H02",
        title="Personalized Home",
        domain=ScreenDomain.HOME,
        route="/home/personalized",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F09",
        requires_auth=True,
        description="Adaptive home feed curated around user's active style identity.",
    ),
    ScreenDefinition(
        screen_id="H03",
        screen_code="H03",
        title="Trending Highlights",
        domain=ScreenDomain.HOME,
        route="/home/trending",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        description="High-velocity micro-trends and viral runway fashion highlights.",
    ),
    ScreenDefinition(
        screen_id="H04",
        screen_code="H04",
        title="Recommended Products",
        domain=ScreenDomain.HOME,
        route="/home/recommended-products",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=True,
        description="Algorithmic product carousel matching user's undertone and budget.",
    ),
    ScreenDefinition(
        screen_id="H05",
        screen_code="H05",
        title="Recommended Looks",
        domain=ScreenDomain.HOME,
        route="/home/recommended-looks",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        description="Complete daily outfit looks assembled by the stylist engine.",
    ),
    ScreenDefinition(
        screen_id="H06",
        screen_code="H06",
        title="Regional Highlights",
        domain=ScreenDomain.HOME,
        route="/home/regional-highlights",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Geo-contextual fashion trends spotlighting the user's metro area.",
    ),
    ScreenDefinition(
        screen_id="H07",
        screen_code="H07",
        title="Recently Viewed",
        domain=ScreenDomain.HOME,
        route="/home/recently-viewed",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=True,
        description="Chronological stream of inspected garments and lookbooks.",
    ),

    # =========================================================================
    # D. Discovery Screens (10 screens) - Dependency Group B: Core Content
    # =========================================================================
    ScreenDefinition(
        screen_id="D01",
        screen_code="D01",
        title="Discovery Home",
        domain=ScreenDomain.DISCOVERY,
        route="/(tabs)/discover",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.TAB,
        feature_id="FX-F03",
        requires_auth=True,
        description="MMR λ=0.7 diversified daily discovery feed with stylist chips.",
    ),
    ScreenDefinition(
        screen_id="D02",
        screen_code="D02",
        title="Explore Fashion",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/fashion",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        description="Visual inspiration browser exploring aesthetics and silhouettes.",
    ),
    ScreenDefinition(
        screen_id="D03",
        screen_code="D03",
        title="Explore Products",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/products",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=False,
        description="Infinite scroll catalog of normalized multi-merchant apparel.",
    ),
    ScreenDefinition(
        screen_id="D04",
        screen_code="D04",
        title="Explore Looks",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/looks",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=False,
        description="Curated head-to-toe looks styled across multiple brands.",
    ),
    ScreenDefinition(
        screen_id="D05",
        screen_code="D05",
        title="Explore Collections",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/collections",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Thematic capsule collections (Quiet Luxury, Scandinavian, Streetwear).",
    ),
    ScreenDefinition(
        screen_id="D06",
        screen_code="D06",
        title="Explore Brands",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/brands",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        description="Directory of merchant and designer fashion brands.",
    ),
    ScreenDefinition(
        screen_id="D07",
        screen_code="D07",
        title="Explore Styles",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/styles",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        description="Fashion archetype explorer traversing aesthetics and subcultures.",
    ),
    ScreenDefinition(
        screen_id="D08",
        screen_code="D08",
        title="Explore Trends",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/trends",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Curated trend stream tracking seasonal silhouettes and colorways.",
    ),
    ScreenDefinition(
        screen_id="D09",
        screen_code="D09",
        title="Personalized Discovery",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/personalized",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F09",
        requires_auth=True,
        description="Hyper-tailored discovery eliminating catalog noise.",
    ),
    ScreenDefinition(
        screen_id="D10",
        screen_code="D10",
        title="Discovery Results",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/results",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        description="Faceted discovery grid filtered by categories, occasions, or tags.",
    ),

    # =========================================================================
    # S. Search Screens (10 screens) - Dependency Group B: Core Content
    # =========================================================================
    ScreenDefinition(
        screen_id="S01",
        screen_code="S01",
        title="Search Home",
        domain=ScreenDomain.SEARCH,
        route="/(tabs)/search",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.TAB,
        feature_id="FX-F04",
        requires_auth=False,
        description="Unified search interface with recent queries and trending tags.",
    ),
    ScreenDefinition(
        screen_id="S02",
        screen_code="S02",
        title="Search Suggestions",
        domain=ScreenDomain.SEARCH,
        route="/search/suggestions",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Real-time prefix tokenized query autocomplete list.",
    ),
    ScreenDefinition(
        screen_id="S03",
        screen_code="S03",
        title="Product Search Results",
        domain=ScreenDomain.SEARCH,
        route="/search/products",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Product-specific matching results grid with sorting controls.",
    ),
    ScreenDefinition(
        screen_id="S04",
        screen_code="S04",
        title="Fashion Search Results",
        domain=ScreenDomain.SEARCH,
        route="/search/fashion",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Search results matching editorial stories and lookbooks.",
    ),
    ScreenDefinition(
        screen_id="S05",
        screen_code="S05",
        title="Brand Search Results",
        domain=ScreenDomain.SEARCH,
        route="/search/brands",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Search results matching fashion brands and merchants.",
    ),
    ScreenDefinition(
        screen_id="S06",
        screen_code="S06",
        title="Style Search Results",
        domain=ScreenDomain.SEARCH,
        route="/search/styles",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Search results matching style archetypes and subcultures.",
    ),
    ScreenDefinition(
        screen_id="S07",
        screen_code="S07",
        title="Trend Search Results",
        domain=ScreenDomain.SEARCH,
        route="/search/trends",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Search results matching active fashion trend keywords.",
    ),
    ScreenDefinition(
        screen_id="S08",
        screen_code="S08",
        title="Search Filters",
        domain=ScreenDomain.SEARCH,
        route="/search/filters",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F04",
        requires_auth=False,
        description="Multi-facet filter sheet covering price, colors, brands, and sizing.",
    ),
    ScreenDefinition(
        screen_id="S09",
        screen_code="S09",
        title="Advanced Search",
        domain=ScreenDomain.SEARCH,
        route="/search/advanced",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Multimodal search allowing image upload and combined query attributes.",
    ),
    ScreenDefinition(
        screen_id="S10",
        screen_code="S10",
        title="Search Empty State",
        domain=ScreenDomain.SEARCH,
        route="/search/empty",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        description="Zero-results fallback with spelling corrections and trending items.",
    ),

    # =========================================================================
    # P. Product Screens (10 screens) - Dependency Group B: Core Content
    # =========================================================================
    ScreenDefinition(
        screen_id="P01",
        screen_code="P01",
        title="Product Listing",
        domain=ScreenDomain.PRODUCT,
        route="/products",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=False,
        description="Canonical product catalog grid with facet chips and pagination.",
    ),
    ScreenDefinition(
        screen_id="P02",
        screen_code="P02",
        title="Product Detail",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=False,
        description="High-information PDP with gallery, price, variants, and primary CTAs.",
    ),
    ScreenDefinition(
        screen_id="P03",
        screen_code="P03",
        title="Product Image Gallery",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id/gallery",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F05",
        requires_auth=False,
        description="Full-screen zoomable high-resolution garment asset gallery.",
    ),
    ScreenDefinition(
        screen_id="P04",
        screen_code="P04",
        title="Product Variant Selection",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id/variants",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F05",
        requires_auth=False,
        description="Interactive colorway swatch and size picker drawer.",
    ),
    ScreenDefinition(
        screen_id="P05",
        screen_code="P05",
        title="Product Reviews",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id/reviews",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=False,
        description="Community reviews, ratings, and physical fit observations.",
    ),
    ScreenDefinition(
        screen_id="P06",
        screen_code="P06",
        title="Product Specifications",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id/specifications",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=False,
        description="Material composition, care guide, fabric weight, and origin.",
    ),
    ScreenDefinition(
        screen_id="P07",
        screen_code="P07",
        title="Similar Products",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id/similar",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=False,
        description="Multimodal vector similarity suggestions matching silhouette.",
    ),
    ScreenDefinition(
        screen_id="P08",
        screen_code="P08",
        title="Recommended Products",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id/recommended",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=True,
        description="Complementary pairing recommendations matching this garment.",
    ),
    ScreenDefinition(
        screen_id="P09",
        screen_code="P09",
        title="Product Comparison",
        domain=ScreenDomain.PRODUCT,
        route="/products/compare",
        template_type=PageTemplateType.COMPARISON,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=False,
        description="Side-by-side spec, pricing, merchant, and fit comparison matrix.",
    ),
    ScreenDefinition(
        screen_id="P10",
        screen_code="P10",
        title="Product Availability",
        domain=ScreenDomain.PRODUCT,
        route="/products/:id/availability",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F05",
        requires_auth=False,
        description="Real-time multi-merchant inventory and stock levels.",
    ),

    # =========================================================================
    # SH. Shopping Screens (12 screens) - Dependency Group C: Advanced Experiences
    # =========================================================================
    ScreenDefinition(
        screen_id="SH01",
        screen_code="SH01",
        title="Shopping Home",
        domain=ScreenDomain.SHOPPING,
        route="/shopping",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        description="Commerce hub with cart preview, saved lists, and deals.",
    ),
    ScreenDefinition(
        screen_id="SH02",
        screen_code="SH02",
        title="Category",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/category/:id",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=False,
        description="Apparel category browser with subcategory filtering pills.",
    ),
    ScreenDefinition(
        screen_id="SH03",
        screen_code="SH03",
        title="Filter",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/filter",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F11",
        requires_auth=False,
        description="Commerce-specific filter covering deals, shipping speed, and sellers.",
    ),
    ScreenDefinition(
        screen_id="SH04",
        screen_code="SH04",
        title="Sort",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/sort",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F11",
        requires_auth=False,
        description="Sort by Price, Popularity, Newest, or Stylist Relevance.",
    ),
    ScreenDefinition(
        screen_id="SH05",
        screen_code="SH05",
        title="Wishlist",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/wishlist",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        description="Saved wishlist with automated price-drop and restock badges.",
    ),
    ScreenDefinition(
        screen_id="SH06",
        screen_code="SH06",
        title="Cart",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/cart",
        template_type=PageTemplateType.CHECKOUT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        description="Unified shopping bag with item quantities and pricing subtotal.",
    ),
    ScreenDefinition(
        screen_id="SH07",
        screen_code="SH07",
        title="Cart Detail",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/cart/detail",
        template_type=PageTemplateType.CHECKOUT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F11",
        requires_auth=True,
        description="Merchant breakdown, estimated taxes, and shipping calculation.",
    ),
    ScreenDefinition(
        screen_id="SH08",
        screen_code="SH08",
        title="Checkout",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/checkout",
        template_type=PageTemplateType.CHECKOUT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        description="Delivery address, payment method, and affiliate handoff launcher.",
    ),
    ScreenDefinition(
        screen_id="SH09",
        screen_code="SH09",
        title="Order Review",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/order-review",
        template_type=PageTemplateType.CHECKOUT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        description="Final pre-submission review of order totals and merchant terms.",
    ),
    ScreenDefinition(
        screen_id="SH10",
        screen_code="SH10",
        title="Order Confirmation",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/order-confirmation",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        description="Success confirmation with tracking tokens and estimated arrivals.",
    ),
    ScreenDefinition(
        screen_id="SH11",
        screen_code="SH11",
        title="Orders",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/orders",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        description="Historical order log across all merchant purchases.",
    ),
    ScreenDefinition(
        screen_id="SH12",
        screen_code="SH12",
        title="Order Detail",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/orders/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        description="Granular order shipment milestones and post-purchase fit survey.",
    ),

    # =========================================================================
    # F. Fashion Content Screens (9 screens) - Dependency Group B: Core Content
    # =========================================================================
    ScreenDefinition(
        screen_id="F01",
        screen_code="F01",
        title="Fashion Home",
        domain=ScreenDomain.FASHION,
        route="/fashion",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Editorial magazine hub curating stories, trends, and lookbooks.",
    ),
    ScreenDefinition(
        screen_id="F02",
        screen_code="F02",
        title="Fashion Feed",
        domain=ScreenDomain.FASHION,
        route="/fashion/feed",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Continuous editorial stream of runway coverage and style guides.",
    ),
    ScreenDefinition(
        screen_id="F03",
        screen_code="F03",
        title="Fashion Story",
        domain=ScreenDomain.FASHION,
        route="/fashion/stories/:id",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Rich visual narrative spotlighting a designer, craft, or aesthetic.",
    ),
    ScreenDefinition(
        screen_id="F04",
        screen_code="F04",
        title="Fashion Article",
        domain=ScreenDomain.FASHION,
        route="/fashion/articles/:id",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="In-depth editorial analysis on fabric innovations and style guides.",
    ),
    ScreenDefinition(
        screen_id="F05",
        screen_code="F05",
        title="Fashion Collection",
        domain=ScreenDomain.FASHION,
        route="/fashion/collections/:id",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Seasonal designer collections with shoppable product links.",
    ),
    ScreenDefinition(
        screen_id="F06",
        screen_code="F06",
        title="Fashion Look",
        domain=ScreenDomain.FASHION,
        route="/fashion/looks/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="High-res editorial look with interactive garment hotspots.",
    ),
    ScreenDefinition(
        screen_id="F07",
        screen_code="F07",
        title="Fashion Inspiration",
        domain=ScreenDomain.FASHION,
        route="/fashion/inspiration",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Moodboard feed driven by color themes and cultural aesthetics.",
    ),
    ScreenDefinition(
        screen_id="F08",
        screen_code="F08",
        title="Brand Story",
        domain=ScreenDomain.FASHION,
        route="/fashion/brands/:id/story",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Behind-the-brand heritage, sustainability ethos, and craftsmanship.",
    ),
    ScreenDefinition(
        screen_id="F09",
        screen_code="F09",
        title="Editorial View",
        domain=ScreenDomain.FASHION,
        route="/fashion/editorial/:id",
        template_type=PageTemplateType.EDITORIAL,
        dependency_group=ImplementationDependencyGroup.GROUP_B_CORE_CONTENT,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F06",
        requires_auth=False,
        description="Immersive full-screen editorial spread.",
    ),

    # =========================================================================
    # ST. Outfit / Styling Screens (9 screens) - Group C: Advanced Experiences
    # =========================================================================
    ScreenDefinition(
        screen_id="ST01",
        screen_code="ST01",
        title="Style Home",
        domain=ScreenDomain.STYLE,
        route="/(tabs)/style",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.TAB,
        feature_id="FX-F07",
        requires_auth=True,
        description="Personal styling studio hub with outfit canvas and saved looks.",
    ),
    ScreenDefinition(
        screen_id="ST02",
        screen_code="ST02",
        title="Outfit Builder",
        domain=ScreenDomain.STYLE,
        route="/style/builder",
        template_type=PageTemplateType.BUILDER,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        description="Interactive 2D drag-and-drop outfit layering canvas.",
    ),
    ScreenDefinition(
        screen_id="ST03",
        screen_code="ST03",
        title="Look Builder",
        domain=ScreenDomain.STYLE,
        route="/style/look-builder",
        template_type=PageTemplateType.BUILDER,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        description="Multi-garment composition tool with compatibility scoring.",
    ),
    ScreenDefinition(
        screen_id="ST04",
        screen_code="ST04",
        title="Mix & Match",
        domain=ScreenDomain.STYLE,
        route="/style/mix-match",
        template_type=PageTemplateType.BUILDER,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        description="Slot-machine carousel rotating tops and bottoms against a base item.",
    ),
    ScreenDefinition(
        screen_id="ST05",
        screen_code="ST05",
        title="Style Recommendation",
        domain=ScreenDomain.STYLE,
        route="/style/recommendations",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Curated algorithmic outfits matching upcoming calendar events.",
    ),
    ScreenDefinition(
        screen_id="ST06",
        screen_code="ST06",
        title="Outfit Preview",
        domain=ScreenDomain.STYLE,
        route="/style/preview/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        description="High-resolution preview of combined outfit components.",
    ),
    ScreenDefinition(
        screen_id="ST07",
        screen_code="ST07",
        title="Outfit Detail",
        domain=ScreenDomain.STYLE,
        route="/style/outfits/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        description="Itemized garment breakdown, total outfit price, and shop-all CTAs.",
    ),
    ScreenDefinition(
        screen_id="ST08",
        screen_code="ST08",
        title="Saved Looks",
        domain=ScreenDomain.STYLE,
        route="/style/saved-looks",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        description="User's personal lookbook of assembled outfits and favorite looks.",
    ),
    ScreenDefinition(
        screen_id="ST09",
        screen_code="ST09",
        title="Style Preferences",
        domain=ScreenDomain.STYLE,
        route="/style/preferences",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        description="Style archetype, color palette, and modesty preferences configuration.",
    ),

    # =========================================================================
    # T. Trends Screens (8 screens) - Dependency Group C: Advanced Experiences
    # =========================================================================
    ScreenDefinition(
        screen_id="T01",
        screen_code="T01",
        title="Trends Home",
        domain=ScreenDomain.TRENDS,
        route="/trends",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Macro and micro trend radar monitoring real-time fashion momentum.",
    ),
    ScreenDefinition(
        screen_id="T02",
        screen_code="T02",
        title="Trending Styles",
        domain=ScreenDomain.TRENDS,
        route="/trends/styles",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Rising aesthetic movements (e.g. Balletcore, Gorpcore, Indie Sleaze).",
    ),
    ScreenDefinition(
        screen_id="T03",
        screen_code="T03",
        title="Trending Products",
        domain=ScreenDomain.TRENDS,
        route="/trends/products",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Products with rapidly spiking demand signals across merchant catalogs.",
    ),
    ScreenDefinition(
        screen_id="T04",
        screen_code="T04",
        title="Trending Categories",
        domain=ScreenDomain.TRENDS,
        route="/trends/categories",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Apparel categories exhibiting seasonal or cyclical breakout growth.",
    ),
    ScreenDefinition(
        screen_id="T05",
        screen_code="T05",
        title="Regional Trends",
        domain=ScreenDomain.TRENDS,
        route="/trends/regional",
        template_type=PageTemplateType.MAP,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Geographic breakdown of style adoption across global metro clusters.",
    ),
    ScreenDefinition(
        screen_id="T06",
        screen_code="T06",
        title="Emerging Trends",
        domain=ScreenDomain.TRENDS,
        route="/trends/emerging",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Early signal detection from runway debuts and boutique ateliers.",
    ),
    ScreenDefinition(
        screen_id="T07",
        screen_code="T07",
        title="Trend Detail",
        domain=ScreenDomain.TRENDS,
        route="/trends/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Deep dive on trend origin, adoption curve, and shoppable expressions.",
    ),
    ScreenDefinition(
        screen_id="T08",
        screen_code="T08",
        title="Trend Timeline",
        domain=ScreenDomain.TRENDS,
        route="/trends/:id/timeline",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        description="Historical popularity trajectory and forecast longevity curve.",
    ),

    # =========================================================================
    # M. Regional / Maps Screens (10 screens) - Group C: Advanced Experiences
    # =========================================================================
    ScreenDefinition(
        screen_id="M01",
        screen_code="M01",
        title="Regional Home",
        domain=ScreenDomain.REGIONAL,
        route="/maps",
        template_type=PageTemplateType.MAP,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Interactive geographic fashion radar with global clusters.",
    ),
    ScreenDefinition(
        screen_id="M02",
        screen_code="M02",
        title="Fashion Map",
        domain=ScreenDomain.REGIONAL,
        route="/maps/fashion",
        template_type=PageTemplateType.MAP,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Full-screen map overlay displaying active regional style signals.",
    ),
    ScreenDefinition(
        screen_id="M03",
        screen_code="M03",
        title="Regional Explorer",
        domain=ScreenDomain.REGIONAL,
        route="/maps/explorer",
        template_type=PageTemplateType.MAP,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Multi-tier geographic navigation from continent to city borough.",
    ),
    ScreenDefinition(
        screen_id="M04",
        screen_code="M04",
        title="Country View",
        domain=ScreenDomain.REGIONAL,
        route="/maps/country/:country_id",
        template_type=PageTemplateType.MAP,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="National fashion trends, domestic designers, and local preferences.",
    ),
    ScreenDefinition(
        screen_id="M05",
        screen_code="M05",
        title="State / Province View",
        domain=ScreenDomain.REGIONAL,
        route="/maps/state/:state_id",
        template_type=PageTemplateType.MAP,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="State-level climate adaptations and local shopping hubs.",
    ),
    ScreenDefinition(
        screen_id="M06",
        screen_code="M06",
        title="City View",
        domain=ScreenDomain.REGIONAL,
        route="/maps/city/:city_id",
        template_type=PageTemplateType.MAP,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Metropolitan street style, boutique clusters, and local events.",
    ),
    ScreenDefinition(
        screen_id="M07",
        screen_code="M07",
        title="Regional Trends",
        domain=ScreenDomain.REGIONAL,
        route="/maps/trends/:region_id",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Trending items specifically adopted within selected geographic zone.",
    ),
    ScreenDefinition(
        screen_id="M08",
        screen_code="M08",
        title="Local Products",
        domain=ScreenDomain.REGIONAL,
        route="/maps/products/:region_id",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Garments sourced from indigenous craftspersons or regional merchants.",
    ),
    ScreenDefinition(
        screen_id="M09",
        screen_code="M09",
        title="Regional Collections",
        domain=ScreenDomain.REGIONAL,
        route="/maps/collections/:region_id",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Curated fashion collections inspired by regional culture or craft.",
    ),
    ScreenDefinition(
        screen_id="M10",
        screen_code="M10",
        title="Location Detail",
        domain=ScreenDomain.REGIONAL,
        route="/maps/location/:location_id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        description="Detailed borough / neighborhood fashion snapshot and boutique list.",
    ),

    # =========================================================================
    # AI. AI Screens (9 screens) - Dependency Group C: Advanced Experiences
    # =========================================================================
    ScreenDefinition(
        screen_id="AI01",
        screen_code="AI01",
        title="AI Home",
        domain=ScreenDomain.AI,
        route="/ai",
        template_type=PageTemplateType.ASSISTANT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Central AI intelligence hub with quick stylist query shortcuts.",
    ),
    ScreenDefinition(
        screen_id="AI02",
        screen_code="AI02",
        title="AI Fashion Assistant",
        domain=ScreenDomain.AI,
        route="/ai/assistant",
        template_type=PageTemplateType.ASSISTANT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Conversational multi-turn fashion advisor with real-time look assembly.",
    ),
    ScreenDefinition(
        screen_id="AI03",
        screen_code="AI03",
        title="AI Product Assistant",
        domain=ScreenDomain.AI,
        route="/ai/products",
        template_type=PageTemplateType.ASSISTANT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Automated product finder and fit suitability evaluator.",
    ),
    ScreenDefinition(
        screen_id="AI04",
        screen_code="AI04",
        title="AI Style Assistant",
        domain=ScreenDomain.AI,
        route="/ai/style",
        template_type=PageTemplateType.ASSISTANT,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Personalized styling advice based on user's Monk skin tone and build.",
    ),
    ScreenDefinition(
        screen_id="AI05",
        screen_code="AI05",
        title="AI Outfit Recommendation",
        domain=ScreenDomain.AI,
        route="/ai/outfit-recommendations",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="AI-synthesized outfits with algorithmic compatibility scoring.",
    ),
    ScreenDefinition(
        screen_id="AI06",
        screen_code="AI06",
        title="AI Search",
        domain=ScreenDomain.AI,
        route="/ai/search",
        template_type=PageTemplateType.DISCOVERY,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Natural language semantic search understanding aesthetic queries.",
    ),
    ScreenDefinition(
        screen_id="AI07",
        screen_code="AI07",
        title="AI Recommendation Detail",
        domain=ScreenDomain.AI,
        route="/ai/recommendation/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Itemized recommendation card with user controls to modify or accept.",
    ),
    ScreenDefinition(
        screen_id="AI08",
        screen_code="AI08",
        title="AI Result Explanation",
        domain=ScreenDomain.AI,
        route="/ai/explanation/:id",
        template_type=PageTemplateType.DETAIL,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F08",
        requires_auth=True,
        description="Transparent 'Why this recommendation?' breakdown of styling logic.",
    ),
    ScreenDefinition(
        screen_id="AI09",
        screen_code="AI09",
        title="AI Preferences",
        domain=ScreenDomain.AI,
        route="/ai/preferences",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_C_ADVANCED_EXPERIENCES,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        description="Controls governing AI autonomy, risk tolerance, and color palette bias.",
    ),

    # =========================================================================
    # PR. Saved / Personal Screens (11 screens) - Group D: Personalization
    # =========================================================================
    ScreenDefinition(
        screen_id="PR01",
        screen_code="PR01",
        title="Profile",
        domain=ScreenDomain.PROFILE,
        route="/(tabs)/profile",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.TAB,
        feature_id="FX-F02",
        requires_auth=True,
        description="Main profile overview with style stats, active avatar, and badges.",
    ),
    ScreenDefinition(
        screen_id="PR02",
        screen_code="PR02",
        title="Personal Dashboard",
        domain=ScreenDomain.PROFILE,
        route="/profile/dashboard",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        description="Activity metrics, wardrobe utilization, and style evolution over time.",
    ),
    ScreenDefinition(
        screen_id="PR03",
        screen_code="PR03",
        title="Saved Products",
        domain=ScreenDomain.PROFILE,
        route="/profile/saved-products",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        description="Bookmarked individual garments across all merchant platforms.",
    ),
    ScreenDefinition(
        screen_id="PR04",
        screen_code="PR04",
        title="Saved Looks",
        domain=ScreenDomain.PROFILE,
        route="/profile/saved-looks",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        description="Assembled outfits and complete looks saved for future reference.",
    ),
    ScreenDefinition(
        screen_id="PR05",
        screen_code="PR05",
        title="Saved Fashion",
        domain=ScreenDomain.PROFILE,
        route="/profile/saved-fashion",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        description="Bookmarked editorial stories, designer collections, and runway articles.",
    ),
    ScreenDefinition(
        screen_id="PR06",
        screen_code="PR06",
        title="Wishlist",
        domain=ScreenDomain.PROFILE,
        route="/profile/wishlist",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        description="Primary shopping wishlist with notifications for discounts and restocks.",
    ),
    ScreenDefinition(
        screen_id="PR07",
        screen_code="PR07",
        title="Recently Viewed",
        domain=ScreenDomain.PROFILE,
        route="/profile/recently-viewed",
        template_type=PageTemplateType.LISTING,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        description="History of all viewed garments, looks, and editorial pieces.",
    ),
    ScreenDefinition(
        screen_id="PR08",
        screen_code="PR08",
        title="Preferences",
        domain=ScreenDomain.PROFILE,
        route="/profile/preferences",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        description="Fashion preferences: sizing, favorite brands, budget, and avoided colors.",
    ),
    ScreenDefinition(
        screen_id="PR09",
        screen_code="PR09",
        title="Recommendation Preferences",
        domain=ScreenDomain.PROFILE,
        route="/profile/recommendation-preferences",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F09",
        requires_auth=True,
        description="Parameters governing recommendation diversity and serendipity.",
    ),
    ScreenDefinition(
        screen_id="PR10",
        screen_code="PR10",
        title="Regional Preferences",
        domain=ScreenDomain.PROFILE,
        route="/profile/regional-preferences",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=True,
        description="Location context overrides, preferred currency, and metric units.",
    ),
    ScreenDefinition(
        screen_id="PR11",
        screen_code="PR11",
        title="Account Settings",
        domain=ScreenDomain.PROFILE,
        route="/profile/settings",
        template_type=PageTemplateType.SETTINGS,
        dependency_group=ImplementationDependencyGroup.GROUP_D_PERSONALIZATION,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        description="Security, notifications, privacy consent, and data erasure controls.",
    ),

    # =========================================================================
    # X. System Screens (10 screens) - Group E: Production Quality
    # =========================================================================
    ScreenDefinition(
        screen_id="X01",
        screen_code="X01",
        title="404 Not Found",
        domain=ScreenDomain.SYSTEM,
        route="/system/404",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Resource not found error screen with smart redirection CTAs.",
    ),
    ScreenDefinition(
        screen_id="X02",
        screen_code="X02",
        title="403 Forbidden",
        domain=ScreenDomain.SYSTEM,
        route="/system/403",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Access restricted / consent required boundary screen.",
    ),
    ScreenDefinition(
        screen_id="X03",
        screen_code="X03",
        title="500 Internal Error",
        domain=ScreenDomain.SYSTEM,
        route="/system/500",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Server exception screen with RFC-7807 trace ID and retry CTA.",
    ),
    ScreenDefinition(
        screen_id="X04",
        screen_code="X04",
        title="Offline",
        domain=ScreenDomain.SYSTEM,
        route="/system/offline",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Device disconnected state displaying cached wardrobe items.",
    ),
    ScreenDefinition(
        screen_id="X05",
        screen_code="X05",
        title="Maintenance",
        domain=ScreenDomain.SYSTEM,
        route="/system/maintenance",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Scheduled maintenance window advisory with service status.",
    ),
    ScreenDefinition(
        screen_id="X06",
        screen_code="X06",
        title="Loading",
        domain=ScreenDomain.SYSTEM,
        route="/system/loading",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Global loading state with brand shimmer placeholders.",
    ),
    ScreenDefinition(
        screen_id="X07",
        screen_code="X07",
        title="Empty",
        domain=ScreenDomain.SYSTEM,
        route="/system/empty",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Universal zero-data fallback screen with exploratory prompts.",
    ),
    ScreenDefinition(
        screen_id="X08",
        screen_code="X08",
        title="Error Recovery",
        domain=ScreenDomain.SYSTEM,
        route="/system/error-recovery",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Step-by-step state recovery and session re-synchronization screen.",
    ),
    ScreenDefinition(
        screen_id="X09",
        screen_code="X09",
        title="Permission",
        domain=ScreenDomain.SYSTEM,
        route="/system/permission",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Hardware camera / photo library / location permission request.",
    ),
    ScreenDefinition(
        screen_id="X10",
        screen_code="X10",
        title="Unsupported State",
        domain=ScreenDomain.SYSTEM,
        route="/system/unsupported",
        template_type=PageTemplateType.DASHBOARD,
        dependency_group=ImplementationDependencyGroup.GROUP_E_PRODUCTION_QUALITY,
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=False,
        description="Device viewport or browser capability mismatch guidance.",
    ),
]

BREAKPOINT_CONFIGS: list[BreakpointConfig] = [
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.XS,
        min_width=0,
        max_width=479,
        columns=4,
        gutter=12,
        margin=16,
        content_max_width=479,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.SM,
        min_width=480,
        max_width=767,
        columns=6,
        gutter=16,
        margin=20,
        content_max_width=767,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.MD,
        min_width=768,
        max_width=1023,
        columns=8,
        gutter=20,
        margin=24,
        content_max_width=960,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.LG,
        min_width=1024,
        max_width=1279,
        columns=12,
        gutter=24,
        margin=32,
        content_max_width=1200,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.XL,
        min_width=1280,
        max_width=None,
        columns=12,
        gutter=32,
        margin=48,
        content_max_width=1440,
    ),
]


def get_screen_inventory() -> ScreenInventoryRegistry:
    return ScreenInventoryRegistry(
        version="1.0.0",
        total_screens=len(CANONICAL_SCREENS),
        screens=CANONICAL_SCREENS,
    )
