"""Master Screen Inventory Catalog for FashXStudio.

Defines the complete canonical inventory of 54 screens across all 12 functional domains,
binding each screen to its underlying Feature Platform capability (FX-F00 through FX-F16).
"""

from schemas.visual.v1 import (
    BreakpointConfig,
    DeviceBreakpoint,
    NavigationType,
    ScreenDefinition,
    ScreenDomain,
    ScreenInventoryRegistry,
)

CANONICAL_SCREENS: list[ScreenDefinition] = [
    # Domain 1: Onboarding & Identity (FX-F02)
    ScreenDefinition(
        screen_id="SCR-ONB-01",
        title="Welcome & Value Proposition",
        domain=ScreenDomain.ONBOARDING,
        route="/onboarding/welcome",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Initial splash and value proposition carousel outlining AI personal styling.",
    ),
    ScreenDefinition(
        screen_id="SCR-ONB-02",
        title="Biometric & Privacy Consent Gate",
        domain=ScreenDomain.ONBOARDING,
        route="/onboarding/consent",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Explicit GDPR/DPDP consent gate for ephemeral portrait processing and 3D body calibration.",
    ),
    ScreenDefinition(
        screen_id="SCR-ONB-03",
        title="Portrait Capture & Quality Inspection Gate",
        domain=ScreenDomain.ONBOARDING,
        route="/onboarding/capture",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=True,
        description="Real-time camera view with posture framing guides, lighting analysis, and sharpness validation.",
    ),
    ScreenDefinition(
        screen_id="SCR-ONB-04",
        title="Monk Skin Tone & Undertone Calibration",
        domain=ScreenDomain.ONBOARDING,
        route="/onboarding/calibration",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=True,
        description="Interactive 10-point Monk Skin Tone (MST) selector with warm/neutral/cool undertone fine-tuning.",
    ),
    ScreenDefinition(
        screen_id="SCR-ONB-05",
        title="Sizing & Fit Baseline Questionnaire",
        domain=ScreenDomain.ONBOARDING,
        route="/onboarding/sizing",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Baseline height, body silhouette archetype, and typical brand sizing references.",
    ),

    # Domain 2: Discovery & Exploration (FX-F03)
    ScreenDefinition(
        screen_id="SCR-DISC-01",
        title="Personalized Discovery Feed",
        domain=ScreenDomain.DISCOVERY,
        route="/(tabs)/discover",
        navigation_type=NavigationType.TAB,
        feature_id="FX-F03",
        requires_auth=True,
        requires_biometric_consent=False,
        description="MMR λ=0.7 diversified daily outfit recommendations with stylist rationale chips.",
    ),
    ScreenDefinition(
        screen_id="SCR-DISC-02",
        title="Trending & Viral Style Radar",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/trending",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Real-time macro/micro fashion trend signals across runway, social, and street fashion.",
    ),
    ScreenDefinition(
        screen_id="SCR-DISC-03",
        title="Curated Capsule Collections",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/capsules",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Editorial thematic capsules (e.g., Quiet Luxury, Scandinavian Minimalist, Techwear).",
    ),
    ScreenDefinition(
        screen_id="SCR-DISC-04",
        title="Category Hub Explorer",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/categories",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Taxonomy browser traversing apparel hierarchies, silhouettes, and fabric types.",
    ),
    ScreenDefinition(
        screen_id="SCR-DISC-05",
        title="Occasion & Weather-Driven Discovery",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/occasions",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Hyper-contextual look generator filtered by user's local climate and calendar events.",
    ),
    ScreenDefinition(
        screen_id="SCR-DISC-06",
        title="Daily Stylist Rationale Feed",
        domain=ScreenDomain.DISCOVERY,
        route="/discover/daily-rationale",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F03",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Deep-dive aesthetic reasoning explaining why today's selected palette flatters user's undertone.",
    ),

    # Domain 3: Search & Exploration (FX-F04)
    ScreenDefinition(
        screen_id="SCR-SRCH-01",
        title="Unified Search & Autocomplete",
        domain=ScreenDomain.SEARCH,
        route="/(tabs)/search",
        navigation_type=NavigationType.TAB,
        feature_id="FX-F04",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Instant search with prefix tokenization, recent query chips, and trending keyword tags.",
    ),
    ScreenDefinition(
        screen_id="SCR-SRCH-02",
        title="Search Results & Faceted Grid",
        domain=ScreenDomain.SEARCH,
        route="/search/results",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Infinite scroll product grid with active facet pill indicators and sorting controls.",
    ),
    ScreenDefinition(
        screen_id="SCR-SRCH-03",
        title="Multi-Dimensional Filter Sheet",
        domain=ScreenDomain.SEARCH,
        route="/search/filters",
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F04",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Comprehensive filter sheet covering price ceiling, brands, colors, neckline, and fit bias.",
    ),
    ScreenDefinition(
        screen_id="SCR-SRCH-04",
        title="Visual Similarity & Camera Search",
        domain=ScreenDomain.SEARCH,
        route="/search/visual",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F04",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Upload/capture garment snapshot to perform 512-dim multimodal vector similarity lookup.",
    ),

    # Domain 4: Product Detail Experience (FX-F05)
    ScreenDefinition(
        screen_id="SCR-PROD-01",
        title="Product Detail Page (PDP)",
        domain=ScreenDomain.PRODUCT,
        route="/product/[id]",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F05",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Hero zoomable gallery, normalized price, merchant source badge, color/size variant swatches.",
    ),
    ScreenDefinition(
        screen_id="SCR-PROD-02",
        title="Size Chart & Fit Recommendation",
        domain=ScreenDomain.PRODUCT,
        route="/product/[id]/size-guide",
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F05",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Centimeter normalized size conversion table coupled with empirical community fit bias.",
    ),
    ScreenDefinition(
        screen_id="SCR-PROD-03",
        title="Merchant Stock & Price Comparison",
        domain=ScreenDomain.PRODUCT,
        route="/product/[id]/merchants",
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F05",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Multi-merchant price comparison table comparing Myntra, Amazon, Flipkart, and Shopify offers.",
    ),
    ScreenDefinition(
        screen_id="SCR-PROD-04",
        title="Stylist Compatibility Rationale",
        domain=ScreenDomain.PRODUCT,
        route="/product/[id]/rationale",
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F05",
        requires_auth=True,
        requires_biometric_consent=False,
        description="AI Stylist breakdown of color harmony, silhouette alignment, and pairing recommendations.",
    ),

    # Domain 5: Virtual Try-On & Fitting Room (FX-F08)
    ScreenDefinition(
        screen_id="SCR-VTO-01",
        title="Virtual Fitting Canvas",
        domain=ScreenDomain.VTO,
        route="/(tabs)/tryon",
        navigation_type=NavigationType.TAB,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=True,
        description="Interactive dressing room canvas displaying user's calibrated avatar and active try-on garments.",
    ),
    ScreenDefinition(
        screen_id="SCR-VTO-02",
        title="Garment Layering & Swap Drawer",
        domain=ScreenDomain.VTO,
        route="/tryon/layers",
        navigation_type=NavigationType.DRAWER,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=True,
        description="Z-index garment stack manager: toggle tops, bottoms, outerwear, footwear, and accessories.",
    ),
    ScreenDefinition(
        screen_id="SCR-VTO-03",
        title="202 Async Try-On Waiting Room",
        domain=ScreenDomain.VTO,
        route="/tryon/progress/[job_id]",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=True,
        description="Live GPU synthesis progress monitor with animated shimmer and step telemetry indicators.",
    ),
    ScreenDefinition(
        screen_id="SCR-VTO-04",
        title="Try-On Inspection & C2PA Provenance",
        domain=ScreenDomain.VTO,
        route="/tryon/result/[render_id]",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=True,
        description="High-res pinch-to-zoom render inspection with cryptographic C2PA AI watermark badge.",
    ),
    ScreenDefinition(
        screen_id="SCR-VTO-05",
        title="Try-On Realism & Fit Feedback Dialogue",
        domain=ScreenDomain.VTO,
        route="/tryon/feedback/[render_id]",
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=False,
        description="1-5 star realism scoring and fit observations (too tight/accurate/too loose) feeding calibration.",
    ),

    # Domain 6: Wardrobe & Digital Closet (FX-F10)
    ScreenDefinition(
        screen_id="SCR-CLST-01",
        title="Digital Wardrobe Grid",
        domain=ScreenDomain.CLOSET,
        route="/(tabs)/closet",
        navigation_type=NavigationType.TAB,
        feature_id="FX-F10",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Virtual closet organized by categories (Tops, Bottoms, Outerwear, Footwear) with filter pills.",
    ),
    ScreenDefinition(
        screen_id="SCR-CLST-02",
        title="Saved Snapshot Item Detail",
        domain=ScreenDomain.CLOSET,
        route="/closet/item/[id]",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Frozen point-in-time pricing, purchase status, high-res render snapshot, and care instructions.",
    ),
    ScreenDefinition(
        screen_id="SCR-CLST-03",
        title="Wardrobe Digitizer & Photo Ingest",
        domain=ScreenDomain.CLOSET,
        route="/closet/digitize",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Auto background removal and attribute tagging camera to digitize user's physical wardrobe.",
    ),
    ScreenDefinition(
        screen_id="SCR-CLST-04",
        title="Wardrobe Color Harmony & Gap Analyzer",
        domain=ScreenDomain.CLOSET,
        route="/closet/analytics",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F10",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Color palette distribution chart, missing essentials radar, and cost-per-wear metrics.",
    ),

    # Domain 7: Outfit & Style Studio (FX-F07)
    ScreenDefinition(
        screen_id="SCR-OUTF-01",
        title="Interactive Outfit Studio",
        domain=ScreenDomain.OUTFIT,
        route="/outfits/studio",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Freeform 2D styling canvas allowing drag-and-drop layering, scaling, and moodboard composition.",
    ),
    ScreenDefinition(
        screen_id="SCR-OUTF-02",
        title="AI Generated Lookbooks",
        domain=ScreenDomain.OUTFIT,
        route="/outfits/lookbooks",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Curated thematic lookbooks automatically assembled using rule-based and multimodal compatibility.",
    ),
    ScreenDefinition(
        screen_id="SCR-OUTF-03",
        title="Mix-and-Match Matrix",
        domain=ScreenDomain.OUTFIT,
        route="/outfits/mix-match",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Slot-machine style horizontal carousel rotating tops, bottoms, and jackets against a base item.",
    ),
    ScreenDefinition(
        screen_id="SCR-OUTF-04",
        title="Occasion Lookbook Builder",
        domain=ScreenDomain.OUTFIT,
        route="/outfits/builder",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F07",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Step-by-step outfit wizard configured for weddings, interviews, date nights, or casual weekends.",
    ),
    ScreenDefinition(
        screen_id="SCR-OUTF-05",
        title="Outfit Publishing & Export Sheet",
        domain=ScreenDomain.OUTFIT,
        route="/outfits/share/[id]",
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F07",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Generates social look cards with embedded affiliate tags and try-on composite badges.",
    ),

    # Domain 8: Shopping, Cart & Commerce (FX-F11)
    ScreenDefinition(
        screen_id="SCR-SHOP-01",
        title="Universal Wishlist & Price Tracker",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/wishlist",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Cross-merchant saved list featuring automated price drop alerts and stock replenish notices.",
    ),
    ScreenDefinition(
        screen_id="SCR-SHOP-02",
        title="Unified Shopping Bag",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/cart",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Aggregated cart showing merchant breakdown, active promotions, and estimated delivery dates.",
    ),
    ScreenDefinition(
        screen_id="SCR-SHOP-03",
        title="Outbound Merchant Affiliate Handoff",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/checkout-handoff",
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F11",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Deterministic tracking token generator (fashx_{uid}_{token}) dispatching directly to merchant checkout.",
    ),
    ScreenDefinition(
        screen_id="SCR-SHOP-04",
        title="Order History & Shipment Tracker",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/orders",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F11",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Multi-merchant shipment status milestones with delivery timeline tracking.",
    ),
    ScreenDefinition(
        screen_id="SCR-SHOP-05",
        title="Post-Purchase Fit Ledger Survey",
        domain=ScreenDomain.SHOPPING,
        route="/shopping/fit-survey/[order_id]",
        navigation_type=NavigationType.MODAL,
        feature_id="FX-F11",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Structured feedback collection driving community brand sizing bias calculations.",
    ),

    # Domain 9: Regional & Geography (FX-F12)
    ScreenDefinition(
        screen_id="SCR-GEO-01",
        title="Global & Regional Fashion Radar Map",
        domain=ScreenDomain.REGIONAL,
        route="/regional/map",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Interactive geographic heatmap visualizing real-time fashion aesthetic clusters across metro areas.",
    ),
    ScreenDefinition(
        screen_id="SCR-GEO-02",
        title="City & Street-Style Micro Hub",
        domain=ScreenDomain.REGIONAL,
        route="/regional/city/[city_id]",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Curated localized fashion feed spotlighting trends in Tokyo, Paris, New York, Milan, Mumbai.",
    ),
    ScreenDefinition(
        screen_id="SCR-GEO-03",
        title="Local Artisan & Boutique Directory",
        domain=ScreenDomain.REGIONAL,
        route="/regional/artisans",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Geographic discovery of indigenous fabrics, regional crafts, and independent sustainable ateliers.",
    ),
    ScreenDefinition(
        screen_id="SCR-GEO-04",
        title="Climate-Adaptive Wardrobe Forecast",
        domain=ScreenDomain.REGIONAL,
        route="/regional/climate",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F12",
        requires_auth=True,
        requires_biometric_consent=False,
        description="7-day weather outlook matched with breathability indices, rain resistance, and layering recommendations.",
    ),

    # Domain 10: AI Intelligence & Stylist Hub (FX-F08)
    ScreenDefinition(
        screen_id="SCR-AI-01",
        title="AI Conversational Fashion Assistant",
        domain=ScreenDomain.INTELLIGENCE,
        route="/ai/assistant",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Context-aware chat assistant capable of multi-turn outfit querying and fashion advice.",
    ),
    ScreenDefinition(
        screen_id="SCR-AI-02",
        title="Color Wheel & Harmony Inspector",
        domain=ScreenDomain.INTELLIGENCE,
        route="/ai/color-harmony",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Visual color wheel displaying complementary, analogous, and triadic garment combinations.",
    ),
    ScreenDefinition(
        screen_id="SCR-AI-03",
        title="Wardrobe Gap & Acquisition Advisory",
        domain=ScreenDomain.INTELLIGENCE,
        route="/ai/wardrobe-gaps",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Mathematical graph analysis highlighting missing versatile items to maximize outfit entropy.",
    ),
    ScreenDefinition(
        screen_id="SCR-AI-04",
        title="Trend Velocity & Lifecycle Predictor",
        domain=ScreenDomain.INTELLIGENCE,
        route="/ai/trends",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F08",
        requires_auth=False,
        requires_biometric_consent=False,
        description="Time-series chart showing whether a micro-trend is emerging, peaking, or saturating.",
    ),

    # Domain 11: Profile, Preferences & Privacy (FX-F02)
    ScreenDefinition(
        screen_id="SCR-PROF-01",
        title="User Style Identity Profile",
        domain=ScreenDomain.PROFILE,
        route="/(tabs)/profile",
        navigation_type=NavigationType.TAB,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Unified profile header, active avatar, style archetype badges, and activity stats.",
    ),
    ScreenDefinition(
        screen_id="SCR-PROF-02",
        title="Style & Brand Preferences Editor",
        domain=ScreenDomain.PROFILE,
        route="/profile/preferences",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Sliders and tag pickers for preferred aesthetics, budget caps, and strictly avoided colors.",
    ),
    ScreenDefinition(
        screen_id="SCR-PROF-03",
        title="Avatar & Biometric Gallery Manager",
        domain=ScreenDomain.PROFILE,
        route="/profile/avatars",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=True,
        description="View, calibrate, or re-take reference portrait photos used for virtual fitting room inference.",
    ),
    ScreenDefinition(
        screen_id="SCR-PROF-04",
        title="Privacy Consent & Cascading Deletion",
        domain=ScreenDomain.PROFILE,
        route="/profile/privacy",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=False,
        description="GDPR/DPDP compliance center with instant consent revocation and cascading hard-erasure triggers.",
    ),
    ScreenDefinition(
        screen_id="SCR-PROF-05",
        title="Settings, Units & Accessibility Options",
        domain=ScreenDomain.PROFILE,
        route="/profile/settings",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F02",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Unit selection (cm/inches), high contrast mode, reduced motion, and notification preferences.",
    ),

    # Domain 12: Admin & Systems Observability (FX-F00)
    ScreenDefinition(
        screen_id="SCR-ADM-01",
        title="Release Gates G1-G6 Verification Console",
        domain=ScreenDomain.ADMIN,
        route="/admin/release-gates",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Live dashboard monitoring G1 functional pass rate, G2 ML calibration, and G3 performance p95.",
    ),
    ScreenDefinition(
        screen_id="SCR-ADM-02",
        title="Catalog Ingestion & dHash Telemetry",
        domain=ScreenDomain.ADMIN,
        route="/admin/catalog-ingestion",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Real-time multi-merchant scraper health, perceptual hash collision rates, and VLM enrich queue.",
    ),
    ScreenDefinition(
        screen_id="SCR-ADM-03",
        title="GPU Worker & Try-On Cache Monitor",
        domain=ScreenDomain.ADMIN,
        route="/admin/vto-telemetry",
        navigation_type=NavigationType.STACK,
        feature_id="FX-F00",
        requires_auth=True,
        requires_biometric_consent=False,
        description="Celery queue length, GPU lease durations, 202 job success rate, and composite SHA cache hit ratio.",
    ),
]

BREAKPOINT_CONFIGS: list[BreakpointConfig] = [
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.XS,
        min_width=0,
        max_width=479,
        columns=4,
        gutter=12,
        margin=16,
        content_max_width=479,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.SM,
        min_width=480,
        max_width=767,
        columns=6,
        gutter=16,
        margin=20,
        content_max_width=767,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.MD,
        min_width=768,
        max_width=1023,
        columns=8,
        gutter=20,
        margin=24,
        content_max_width=960,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.LG,
        min_width=1024,
        max_width=1279,
        columns=12,
        gutter=24,
        margin=32,
        content_max_width=1200,
    ),
    BreakpointConfig(
        breakpoint=DeviceBreakpoint.XL,
        min_width=1280,
        max_width=None,
        columns=12,
        gutter=32,
        margin=48,
        content_max_width=1440,
    ),
]


def get_screen_inventory() -> ScreenInventoryRegistry:
    return ScreenInventoryRegistry(
        version="1.0.0",
        total_screens=len(CANONICAL_SCREENS),
        screens=CANONICAL_SCREENS,
    )
