"""Registered contracts for the FashXStudio 16-phase feature programme."""

from .foundation import FeatureDefinition

FEATURE_CATALOG: tuple[FeatureDefinition, ...] = (
    FeatureDefinition("FX-F00", "Feature Production Baseline", "1.0.0"),
    FeatureDefinition(
        "FX-F01",
        "Feature Foundation",
        "1.0.0",
        dependencies=("FX-F00",),
        capabilities=(
            "feature_registry",
            "feature_runtime",
            "feature_events",
            "feature_dependencies",
        ),
    ),
    FeatureDefinition(
        "FX-F02",
        "User & Onboarding",
        "1.0.0",
        description="User onboarding, profile and mutable fashion preferences.",
        dependencies=("FX-F01",),
        capabilities=("user_profile", "onboarding", "fashion_preferences"),
        events=(
            "onboarding.started",
            "onboarding.updated",
            "onboarding.completed",
            "profile.updated",
        ),
    ),
    FeatureDefinition(
        "FX-F03",
        "Fashion Discovery",
        "1.0.0",
        dependencies=("FX-F02",),
        capabilities=("fashion_feed", "categories", "trends", "collections", "discovery_ranking"),
        events=("discovery.opened", "discovery.item_viewed", "discovery.item_saved"),
    ),
    FeatureDefinition(
        "FX-F04",
        "Search & Exploration",
        "1.0.0",
        dependencies=("FX-F01", "FX-F02", "FX-F03"),
        capabilities=("search", "search_suggestions", "filters", "sorting", "fashion_exploration"),
        events=("search.started", "search.completed", "search.result_selected"),
    ),
    FeatureDefinition(
        "FX-F05",
        "Product Experience",
        "1.0.0",
        dependencies=("FX-F01", "FX-F02", "FX-F03", "FX-F04"),
        capabilities=(
            "product_detail",
            "product_variants",
            "product_availability",
            "fashion_metadata",
            "related_products",
        ),
        events=("product.viewed", "product.saved", "product.variant_selected", "product.action"),
    ),
    FeatureDefinition(
        "FX-F06",
        "Fashion Content",
        "1.0.0",
        dependencies=("FX-F01", "FX-F02", "FX-F03", "FX-F04", "FX-F05"),
        capabilities=(
            "fashion_content",
            "content_templates",
            "lookbooks",
            "style_guides",
            "content_publishing",
            "product_linking",
            "outfit_linking",
        ),
        events=("content.created", "content.viewed", "content.published", "content.action"),
    ),
    FeatureDefinition(
        "FX-F07",
        "Outfit System",
        "1.0.0",
        dependencies=("FX-F01", "FX-F02", "FX-F03", "FX-F04", "FX-F05", "FX-F06"),
        capabilities=(
            "outfit_composition",
            "outfit_templates",
            "product_references",
            "outfit_validation",
        ),
        events=(
            "outfit.created",
            "outfit.updated",
            "outfit.item_added",
            "outfit.viewed",
            "outfit.action",
        ),
    ),
    FeatureDefinition(
        "FX-F08",
        "Fashion Intelligence",
        "1.0.0",
        dependencies=("FX-F01", "FX-F02", "FX-F03", "FX-F04", "FX-F05", "FX-F06", "FX-F07"),
        capabilities=(
            "product_analysis",
            "outfit_analysis",
            "style_analysis",
            "compatibility_analysis",
            "fashion_recommendations",
            "explainable_intelligence",
        ),
        events=("intelligence.requested", "intelligence.completed", "intelligence.feedback"),
    ),
    FeatureDefinition(
        "FX-F09",
        "Personalization",
        "1.0.0",
        dependencies=(
            "FX-F01",
            "FX-F02",
            "FX-F03",
            "FX-F04",
            "FX-F05",
            "FX-F06",
            "FX-F07",
            "FX-F08",
        ),
        capabilities=(
            "preference_signals",
            "profile_weights",
            "personalized_ranking",
            "explanations",
        ),
        events=(
            "personalization.signal_recorded",
            "personalization.profile_updated",
            "personalization.ranking_generated",
        ),
    ),
    FeatureDefinition(
        "FX-F10", "Shopping Intelligence", "1.0.0", dependencies=("FX-F09",),
        capabilities=("wishlist", "comparison"), events=("shopping.item_saved", "shopping.compared"),
    ),
    FeatureDefinition(
        "FX-F11", "Commerce Flow", "1.0.0", dependencies=("FX-F10",),
        capabilities=("cart", "order_lifecycle", "checkout_boundary"), events=("order.created",),
    ),
    FeatureDefinition(
        "FX-F12", "Regional & Geography", "1.0.0", dependencies=("FX-F03",),
        capabilities=("regional_context", "climate_context"), events=("regional.context_updated",),
    ),
    FeatureDefinition(
        "FX-F13", "Engagement", "1.0.0", dependencies=("FX-F06",),
        capabilities=("likes", "follows", "reviews", "sharing"), events=("engagement.recorded",),
    ),
    FeatureDefinition(
        "FX-F14", "Cross-Feature Integration", "1.0.0", dependencies=("FX-F11", "FX-F12", "FX-F13"),
        capabilities=("workflows", "adapter_orchestration", "idempotent_execution"),
    ),
    FeatureDefinition("FX-F15", "Production QA & Validation", "0.1.0", dependencies=("FX-F14",)),
    FeatureDefinition("FX-F16", "Final Production Build", "0.1.0", dependencies=("FX-F15",)),
)
